32blit/graphics/mode7.cpp, 32blit/graphics/surface.cpp
Due to some missing includes the engine code does not compile under OS X.
This PR fixes those issues.
=> Include missing headers to fix compilation issues under OS X.

32blit-sdl/CMakeLists.txt, 32blit-sdl/Main.hpp, 32blit-sdl/Renderer.cpp
libBlitHalSDL.a contains SDL_main, which is required by libSDL2.a.
But libBlitHalSDL.a also depends on libSDL2.a, so we have a circular
dependency. Which ever one is listed first will have some required
symbols stripped by the linker. In order to avoid this, just use
--whole-archive when linking libBlitHalSDL.a, because we almost
certainly need all of it anyway.
This whole situation happens because it is rather unusual to have
main() inside a static library, rather than the source of the final
executable. But due to what we're doing, we doing have much choice.
Fixes #26
=> Sdl main fix

tools/asset-builder, tools/sprite-builder
Asset building for an RGB sprite sheet was failing due to attempt to assign non-existent alpha var.
=> Remove alpha var from RGB getpixel

32blit.toolchain
Fixes this error when using VS Code with the CMake Tools extension:
> The path to the compiler for one or more source files was not found in the CMake cache. If you are using a toolchain file, this probably means that you need to specify the CACHE option when you set your C and/or C++ compiler path
=> Store compilers in the CMake cache

32blit-stm32/CMakeLists.txt, 32blit.toolchain, examples/CMakeLists.txt
Also fixes the renamed fire directory in examples and adds a new
variable for the size tool instead of hard-coding it.
=> Build DFU files automatically as part of the build

mingw.toolchain
This rather long-winded approach includes a work-around for the fact that SDL2_PREFIX doesn't appear to normally be available to the .toolchain file.
It now checks SDL2_DIR, sets it to the README.md mentioned default if not set and imports sdl2-config.cmake to set these variables.
With SDL2_PREFIX it's now possible to copy SDL2.dll into the build output folder automagically.
Maybe there's a better way to do this?
=> Copy SDL2.dll for Windows builds

32blit-sdl/Main.cpp
When using the SDL version to run locally, changed the window title to show more dedication to the 32blit :-)
=> Changed the window title to something more appropriate

tools/sprite-builder
Added arrayname command line option to allow for the naming of the generated packed_data array; useful for projects that aren't working from a single spritesheet for all their graphics data.
=> New option added to spritebuilder

32blit.toolchain
CMAKE_RANLIB and CMAKE_AR were not being set.
This was defaulting to /usr/bin/ranlib and /usr/bin/ar.
=> Wrong ranlib and ar being used.

32blit-sdl/CMakeLists.txt
This gets Visual Studio builds working using the CMake integration + vcpkg and theoretically anyone else that builds SDL with CMake instead of autotools...
(I'll attempt to write some docs for using this with VS after the other VS support gets merged.)
=> Handle SDL2 built with CMake

vs/game/game.vcxproj
Or, apply #60 to #57. Not at a Windows machine right now, but `surface.hpp` is probably generating an error about `__attribute__`.
=> Apply VS cleanups to template

32blit-sdl/System.cpp
Was going to use `SDL_LogMessageV(SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_PRIORITY_DEBUG, psFormatString, args);` but that doesn't return the characters written. So currently both implementations are the same.
=> Implement blit::debugf for SDL

32blit-stm32/Src/32blit.c
The variable holding the current screen mode inside the STM32 HAL is not static - this means users cannot have any variable named mode otherwise a collision occurs. Fix the problem by making this variable static.
=> Make mode static to avoid collisions

vs/game/CMakeLists.txt
Noticed that the empty game solution for Visual Studio was missing a CMakeLists.txt so have added one.
=> Add CMakeLists.txt for Empty Visual Studio Game Solution.

32blit-sdl/Audio.cpp, 32blit-sdl/Audio.hpp, 32blit-sdl/Main.cpp
Stuff I mentioned yesterday and a tiny cleanup. There's still no audio in Chrome without a workaround. (See https://github.com/emscripten-ports/SDL2/issues/57, which I should probably fix in SDL at some point.)
=> A few SDL audio fixes

docs/32blit.md, docs/Emscripten.md, docs/Linux.md, docs/VideoCapture.md, docs/Windows.md, docs/macOS.md
-B isn't supported until CMake 3.13, which is newer than the version in Ubuntu 18.04 which is used in WSL. :cry:
=> Unshorten CMake instructions

examples/scrolly-tile/scrolly-tile.cpp
There's a conflicting `random` in stdlib.h and an exception is being thrown for attempting to convert a negative float to an unsigned integer.
=> Fix scrolly-tile Emscripten build

32blit/engine/utility.cpp, 32blit/engine/utility.hpp
Two simple changes that should help to avoid dynamic allocation and string copying when using the TGA-related functions.
=> Improve tga functions

examples/timer-test/CMakeLists.txt
Adds the missing `CMakeLists.txt` file for the `timer-test` example.
=> Add CMakeLists.txt for timer-test

32blit/engine/audio.cpp, 32blit/engine/audio.hpp, examples/audio-test/audio-test.cpp, examples/scrolly-tile/scrolly-tile.cpp
This set of changes includes several improvements to the audio engine, and some breaking name changes:
* Now uses a state-machine to handle the envelope generation
* The envelope generator now uses frame timing, rather than trying to work in milliseconds
* attack/decay/sustain/release are converted into frame timings as the state-machine progresses
* The last ADSR value is observed when progressing to the next phase, avoiding pops/clicks
* `AudioVoice` is now `Waveform`
This should fix the issue raised in #113 in addition to preventing any unwanted, jarring transitions between envelope states.
=> Audio Improvements

examples/logo/logo.cpp, examples/matrix-test/matrix-test.cpp, examples/sprite-test/sprite-test.cpp
Fixes the build if targeting the internal flash
=> Delete unused variables to avoid wasting flash space

32blit-stm32/Src/gpio.cpp
Pin 5 of port C is the joystick button and setting no pull-up on it
causes it to float.
=> Blue LED is pin 5 of port B, not port C

.travis.yml
Caches the SDL downloads to avoid build failure. Also enables ccache for Linux/STM32/MinGW. (The last commit was mainly for debugging).
=> Travis caching

.travis.yml, tools/src/CMakeLists.txt
Title says it all, really. This will now attach files to our tagged releases so users can just grab a set of prebuilt binaries.
=> Enable Deployment for Win64, Lin64 and STM32 from Travis CI

32blit-sdl/CMakeLists.txt
Should allow find_package to work properly when the framework isn't used.
=> Fix macOS SDL find fallback

docs/macOS.md
Added gcc-arm-none-eabi install instructions using a 3rd party brew source. Not sure if there is a better way that we prefer to get this from, but it's worked for me ok and just installs from the original source 'under the hood'.
=> Added macos gcc-arm-none-eabi install instructions

docs/VSCode.md
An initial configure is needed for the IntelliSense setup, should help #139. Also adds some instructions for building and running.
(I checked and debug is `Ctrl` + `F5` even on macOS.)
=> Expand VS Code docs

.travis.yml, 32blit-sdl/CMakeLists.txt, vs/sdl/sdl2-config.cmake
This removes the need to rename folders for the x86 build and also makes it usable in VS Code with Ninja. Should help with windows problems from #139.
=> Windows SDL cmake config improvements

32blit-stm32/CMakeLists.txt
This is pretty much the only thing preventing doing an arm build on windows. The PythonInterp module is deprecated, but the replacement isn't available until CMake 3.12.
=> Find python and use it to execute the dfu script

32blit-sdl/CMakeLists.txt, 32blit-stm32/CMakeLists.txt, 32blit.toolchain, mingw.toolchain
This is an attempt at adding support for linking binary assets, so that map data, graphics, sound, or other useful bits and bobs can be appended to a binary without having to deal with header files.
It's used by invoking `blit_asset` in an example/project CMakeLists.txt.
`blit_asset` takes two arguments:
1. The project name
2. The binary file to link into the project
For example, to link the audio `rising.raw` into `doom-fire` I might use: `blit_asset (doom-fire rising.raw)`
There's a much more interesting take on this by @Daft-Freak - https://github.com/Daft-Freak/32blit-beta/commit/a373fa4c096a86dff6d65fd3298db1a176b0a4db
Which introduces the concept of executing a packer tool (in this case our `sprite-builder`) to perform build-time conversion of assets. This is *really* cool since it …
=> Add support for linking binary assets

32blit-sdl/System.cpp
=> Remove unused variable from SDL GetUsTimer

firmware/flash-loader/flash-loader.hpp
Okay this one really got us.
We were flashing a ~2MB voxel example via the Flash Loader using the old firmware on Jon's blit.
It worked *fine*. Then I rolled up and said "hey try changing the SD card scalar, it'll flash and load so much quicker."
After flashing the latest firmware, the 2MB file suddenly wouldn't copy over.
I traced the issue back to https://github.com/pimoroni/32blit-beta/commit/c94848851ac7d251da30a67e1111b9e0e92655e6
"What on earth does this seemingly innocuous set of changes have to do with saving to SD card?" I hear you ask.
Well, it turns out the only relevant change was `MAX_FILENAMES` being adjusted from 30 to 24.
This made the difference between the code just scraping by and working on a fluke with Jon's oversized file, and it simply bailing out altogether. We …
=> Allow longer file size in flash loader

32blit/graphics/font.cpp, 32blit/graphics/font.hpp, 32blit/graphics/text.cpp
Also stores the widths of individual characters to avoid having to loop through the character data when measuring.
Here's a slightly modified 2x version of minimal_font:
And my attempt at drawing a font (which is surprisingly not that bad):
(Doesn't add any new fonts)
=> Add support for different sized fonts.

32blit/CMakeLists.txt
Using a glob prevents CMake from reconfiguring automatically when a file is added or removed.
=> List files for the BlitEngine target

32blit-stm32/Inc/32blit.h, 32blit-stm32/Inc/persistence.h, 32blit-stm32/STM32H750VBTxEXT_FLASH.ld, 32blit-stm32/STM32H750VBTx_FLASH.ld, 32blit-stm32/Src/32blit.c, 32blit/engine/output.cpp, firmware/flash-loader/flash-loader.cpp, firmware/flash-loader/flash-loader.hpp
This PR now reflects what I want out of system setting persistence.
We have 1K of volatile memory reserved in `RAM_D3` (which hilariously gives us a 63K leftover in D2 and a 63K leftover in D3. Balance is restored) by the linker scripts.
We then create a struct; `Persist` like so:
```c
struct Persist {
uint32_t magic_word;
float volume;
float backlight;
uint32_t selected_menu_item;
uint32_t reset_target;
};
```
And tell the linker to place it in the uninitialised memory section we've set aside:
```c
__attribute__((section(".persist"))) Persist persist;
```
The `magic_word` is a sentinel value that lets us determine if the RAM has been initialised to a known good state. We check this on init and apply defaults if it's just random garbage:
```c
if(persist.magic_word != …
```
=> Add crude remember-last-menu-item feature to firmware

32blit-sdl/CMakeLists.txt, 32blit-stm32/CMakeLists.txt, 32blit.cmake
This change combines the asset build functions from SDL and STM32 into a single function in 32blit.cmake.
Additionally the library target is renamed to `asset_${ASSET}` to avoid a circular dependency being triggered when the custom command depends upon `${ASSET}`.
=> Rebuild stale assets, move to 32blit.cmake to avoid duplication

mingw.toolchain
These steps don't belong in mingw.toolchain.
Since duplicate commands already exist in 32blit-sdl's CMakeLists.txt it makes sense to invoke them by setting `SDL2_DLL`
Right now they still make potentially incorrect assumptions about where SDL2.dll is located, but this assumption *should* be correct for all versions of SDL2 that have been cross-compiled as per the docs.
=> Remove configure and install steps for SDL2.dll

32blit-sdl/CMakeLists.txt
For some reason despite CMake purportedly creating a `<TARGET_NAME>_BINARY_DIR` for each target, this value wasn't being set in my build using VSCode, CMake Tools and the Visual Studio kit.
I had to swap to `CMAKE_BINARY_DIR` which shoud accomplish the same thing.
Keen to know if this breaks anyone's local builds (or Travis)
=> Fix for 32blit_BINARY_DIR not set for MSVC builds

.travis.yml
One for the next release. Much smaller than the MinGW build. The Travis cache may need cleared to get a new enough sdl2-config to set the dll path.
(Example: https://github.com/Daft-Freak/32blit-beta/releases/download/t3/32blit-beta-t3-211-WIN64.zip)
=> Use Visual Studio to deploy Windows builds

32blit.toolchain
Cleanup https://github.com/pimoroni/32blit-beta/commit/efabdbdacd3f5a5eda0526957087280462bc5ed9#diff-4d6fa8f73bd863c9d065f958fcc0a3ac a bit.
- `-fpermissive` is already in `32blit-stm32/CMakeLists.txt` (see 2b835012bbea2e36e6360115b1f5932c7d8c6dfe)
- `-fpermissive` isn't a valid flag for compiling C (only C++)
- `-Wmisleading-indentation` enables the warning (and doesn't do anything since it's already enabled). It's disabled for the appropriate file in `32blit-stm32/CMakeLists.txt`
=> Warning cleanup cleanup

32blit/graphics/font.hpp
The global constructor would reference the font data, preventing it from being discarded. Doing it at compile time avoids this.
=> Fix discarding unused fonts

32blit/engine/file.hpp
Wraps the existing API in a class. I think this is a bit nicer (okay, I mainly did this because I kept forgetting to close files...).
```c++
int32_t file = blit::open_file("some.thing")
blit::read_file(file, ...);
return; // oops
```
->
```c++
blit::File file("some.thing")
file.read(...);
return; // yay, destructors
```
Guess the next step would be to make the old API internal...
=> Class based file API

32blit/graphics/text.cpp
...and I find another font/text issue. The old code would check if the next character was a newline and skip it, which would fail if there were consecutive newlines (it would treat the additional newlines as spaces).
=> Fix measure text for multiple consecutive newlines

32blit.cmake
Thanks to @Daft-Freak for suggesting this approach here - https://github.com/pimoroni/32blit-beta/issues/212 - and providing the core of the CMake output functionality for the 32blit tool.
=> Add blit_assets_yaml heavily borrowed from @Daft-Freak

32blit.cmake
Makes sure a rebuild is triggered when editing the config for an asset.
(I always seem to run into the weird corner cases...)
=> Make asset packing also depend on the yaml

32blit-sdl/File.cpp
Helps if you pass the path to stat instead of the filename... Must have tested on a dir in the working dir.
=> Fix the symlink fix

32blit-stm32/Src/CDCCommandStream.cpp
Hopefully this will fix the getting stuck at 99% problem when sending data to the 32Blit.
I also tested with removing the Sleep() at the end of the 32Blit app but that still causes issues fo it went back in!
I'm currently running a test with the 32Blit executable in a loop, so far it is at 230 times without a problem so I think this is probably now fixed.
=> Hopefully fix the 99% send over CDC.

32blit/engine/engine.hpp
Including two for the same thing. Neither of these are defined anywhere.
=> Clean up some unused declarations in engine.hpp

.travis.yml, 32blit-sdl/CMakeLists.txt, 32blit-sdl/JPEG.cpp, 32blit-stm32/CMakeLists.txt, 32blit-stm32/Inc/jpeg.h, 32blit-stm32/Inc/jpeg_utils_conf.h, 32blit-stm32/Inc/stm32h7xx_hal_conf.h, 32blit-stm32/Src/jpeg.c, 32blit-stm32/Src/jpeg.cpp, 32blit-stm32/Src/main.c, 32blit-stm32/Utilities/JPEG/jpeg_utils.c, 32blit-stm32/Utilities/JPEG/jpeg_utils.h, 32blit-stm32/Utilities/JPEG/jpeg_utils_conf_template.h, 32blit/graphics/jpeg.hpp, docs/Linux.md, docs/Windows-VisualStudio.md, vs/32blit-sdl/32blit-sdl.vcxproj, vs/32blit-sdl/32blit-sdl.vcxproj.filters, vs/sdl/README.md
Using the hardware decoder (+SDL support).
Adds two functions:
```c++
JPEGImage decode_jpeg_buffer(uint8_t *ptr, uint32_t len);
JPEGImage decode_jpeg_file(std::string filename);
```
Also adds SDL_image as a dependency for 32blit-sdl. It's a bit annoying as it has no CMake config and there is only a find module for v1, had to do some semi-manual detection.
Draft for a few reasons:
- I don't know if anyone else has a use for this
- ~It includes the mass storage/SD changes (was testing while working on this, haven't rebased back to master)~
- Doesn't update the docs for the new dependency (SDL_image)
- ~Also haven't updated VS, still builds as nothing is using the new stuff~
- ~This is going to break Travis when merged until the cache is cleared (no SDL_image in cache).~
=> JPEG decoding

docs/macOS.md
Recent Jpeg code requires SDL IMage. This describes how to install it on macOS
=> Update macOS documentation to source SDL2 and SDL2_Image from homebrew

32blit-sdl/CMakeLists.txt
Shared/static SDL have different target names, if the shared library wasn't built we would fall back to the old `_INCLUDE_DIRS`/`_LIBRARIES` path and find nothing. (#231)
=> Handle SDL built with CMake with only a static library

32blit/graphics/font.hpp
Not very exiting on its own... Takes an array like this:
```
"FONT" (4 bytes)
number of characters (1 byte)
fixed character width (1 byte)
character height (1 byte)
vertical spacing (1 byte)
variable character widths (1 byte per character)
character data (fixed w * ((height + 7) / 8) bytes per character)
```
=> Add a new font constructor

32blit-stm32/CMakeLists.txt
This adds slightly less than 10k to the .bin and makes `printf("%f")` and `std::to_string(1.0f)` work.
=> Enable float formatting for ext flash builds

32blit-stm32/Inc/stm32h7xx_it.h, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/display.cpp, 32blit-stm32/Src/gpio.cpp, 32blit-stm32/Src/main.c, 32blit-stm32/Src/stm32h7xx_it.c
This changes the home button behaviour from polling in the main loop to triggering on an interrupt.
It defines two behaviours:
1. Short press = Open/Close system menu
2. Long press (500ms) = Immediately reset to firmware (only happens in app)
The latter is to replace the force-of-habit "press reset to return to system menu" with a more sensibly defined behaviour, since the reset button will not be so easily accesible on final units.
The former fixes the horrible bounce issue on the menu button.
TODO: Disable button interrupt when switching exe, because it breaks horribly (read: drops to `Default_Handler`) when apps don't define the interrupt vector but the interrupt is still enabled.
=> Interrupt on GPIO_PIN_5 for system menu

32blit-stm32/Src/jpeg.cpp
Wrapping the include in `extern "C"` isn't the nicest way to handle this, but jpeg_utils.h is a generated file. Missed this since there are no users in the repo.
=> Fix JPEG decoding after the compiler changes

32blit.toolchain, 32blit/engine/tweening.cpp, 32blit/graphics/mode7.cpp, 32blit/types/map.cpp, examples/flight/flight.cpp, examples/hardware-test/hardware-test.cpp, examples/palette-cycle/palette-cycle.cpp, examples/palette-swap/palette-swap.cpp, examples/particle/particle.cpp, examples/raycaster/raycaster.cpp, examples/scrolly-tile/scrolly-tile.cpp, examples/tilemap-test/tilemap-test.cpp, examples/timer-test/timer-test.cpp, examples/tunnel/tunnel.cpp, examples/tween-test/tween-test.cpp, examples/voxel/voxel.cpp
Since inadvertent float-to-double promotion can have serious performance implications on 32Blit hardware, I have promoted the warning to an error and fixed the current `double-promotion` errors.
=> Force double-promotion to a compiler error

examples/raycaster/raycaster.cpp, examples/raycaster/raycaster.hpp
The compiler tweaks caused some bizarre (presumably overflow) behaviour in Raycaster that I've fixed.
I've also taken the opportunity to drop `#define` in favour of `constexpr` to give constant values an explicit type.
=> Fix Raycaster weirdness

32blit-stm32/Inc/i2c-bq24295.h, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/i2c-bq24295.c, 32blit/engine/input.hpp, examples/hardware-test/hardware-test.cpp
This change combines the status/fault register retrival into a single transaction of the two bytes. Not only is it less overhead, but puts us in a good position to pull this data using interrupt-driven i2c transactions.
=> Retrieve battery status and fault in single transaction

32blit-stm32/Inc/stm32h7xx_it.h, 32blit-stm32/Inc/tim.h, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/main.c, 32blit-stm32/Src/stm32h7xx_it.c, 32blit-stm32/Src/tim.c
This change uses Timer 2 to enhance the clunky button debounce and long press code so we don't need to mess around comparing a time value to `HAL_GetTick()`.
=> Use TIM2 for sys button debounce, long press

32blit-stm32/Src/32blit.c
A small change that avoids the timer being reset during the "bounce" phase, where the interrupt might fire in quick succession and cause a fake short button press. The system menu button seems to be rock soild now! (It's really hard to test for a negative)
=> Do not restart timer on bounce

32blit-stm32/Src/32blit.c
Found a weird bug where Particle would start in lores, even though init set hires mode. This was because the button state was (correctly) carrying over in the shared-memory API from the firmware to the user code and immediately triggering the resolution switch.
This ensures user code gets a fresh button state.
=> Reset button state before launching app

32blit.toolchain
Decreases code size, also libstdc++_nano is already compiled with this.
=> Add -fno-exceptions to the toolchain

32blit/engine/api.cpp, 32blit/engine/api_private.hpp
Possibly fixes the OpenOCD flashing problem.
=> Avoid initialising the API struct

32blit/engine/file.hpp
`blit::File f("blah", blit::OpenMode::write)` now doesn't ignore you and open the file for reading instead... (Oops, again.)
=> Fix opening files for writing through the constructor

.travis.yml
Displays the change in the size of the firmware in PRs.
Example: https://github.com/Daft-Freak/32blit-beta/pull/1
(Discovered the script this is based on by accident while messing around with Travis/the GitHub API for something else...)
EDIT: Requires a `GITHUB_TOKEN` to be set with the `repo:status` scope.
=> Travis firmware size reporting

32blit-sdl/System.cpp, 32blit-stm32/Inc/display.hpp, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/display.cpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp, 32blit/engine/engine.hpp
This was mostly a result of trying to get DOOM running again after the RGB888 framebuffer change. It seems to work but may need some adjusting. (The menu is a bit of a mess but there...)
Using a simple copy for flip as the DMA2D code had a few too many magic numbers for me to understand. Also, uses the last part of the LTDC section to give the heap some extra room. (Since the allocator would try to use it anyway.)
=> Paletted screen mode

.travis.yml, docs/Windows-WSL.md
Uses a PPA containing GCC/newlib backported from Ubuntu 19.10. I'm not planning on changing anything in there so it should be stable. Also adds the PPA to the WSL instructions.
The main reason for this is that Ubuntu 18.04 has GCC 6.3 and GCC 7 is required for most of C++17. 
https://gcc.gnu.org/projects/cxx-status.html#cxx17
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017
=> Use a newer toolchain for Travis STM32 builds

32blit-stm32/Src/sound.cpp
Was ~21633Hz, should now be ~22048Hz (I think...). Seems to be an improvement in music-player and causes something else I'm doing to have less timing issues.
=> More accutate audio timer

README.md
Python3 / the tools are now required and DFU stuff is only needed if you're working with the firmware.
(WSL/Ubuntu VM requirement probably needs adjusting, but there aren't instructions for setting up a native toolchain... yet)
=> Adjust readme requirements

32blit-stm32/Src/fatfs_sd.c
it would fail after writing all the data as `resp` is uninitialised when sending a stop token.
(More bugs in the SD card code, yay)
=> Fix multi-block SD card writes

32blit-stm32/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_adc.h
`#define` out `register` when compiling `stm32h7xx_ll_adc.h` as C++. This file gets included indirectly by anything using the HAL, which causes a total of over 1000 warnings. This is a little annoying.
This should be entirely safe as GCC only obeys `register` when not optimising (or some other cases that don't apply here, see: https://gcc.gnu.org/onlinedocs/gcc/Hints-implementation.html)
=> "Fix" ~1000 warnings

32blit-stm32/Inc/32blit.h
These either don't exist, or are also declared where they're used.
=> Cleanup declarations in 32blit.h

template/game.vcxproj, vs/examples/voxel/voxel.vcxproj
The game template did not compile under VS2019. The other projects were using C++17 settings. I changed this to the game template as well.
=> Fixed: Game template did not compile with VS2019

examples/audio-test/CMakeLists.txt, examples/audio-wave/CMakeLists.txt, examples/voxel/CMakeLists.txt
This one was missed since it hadn't been bumped to 3.1. Pointed out by @lenardg.
=> Update voxel CMakeLists to 3.8

32blit-stm32/Src/quadspi.c
Switches to 32bit addresses as 24 is one too short. Tested with a modified bin flashed to the very end of the flash. (And a WIP "installed" list).
=> Fix using the second half of the flash

32blit-stm32/Inc/USBManager.h, 32blit-stm32/Src/32blit.c, firmware/flash-loader/flash-loader.cpp
I said that the button rework shouldn't break anything... It did.
This fixes flash-loader to check buttons in `update` instead of `render`, so that `buttons.changed` actually works. Also includes some changes to make it possible to get out of mass storage mode if USB is not connected... and a random warning fix (for a silly warning...)
=> Fix buttons in flash-loader + a few other firmware/flash-loader bits

32blit/graphics/surface.hpp, 32blit/graphics/text.cpp
Avoids string copying, especially when using horizontal alignment.
=> Use string_view for text functions

32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/file.cpp, 32blit/engine/api_private.hpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp
Fixes `file/directory_exists` on SDL (ignored base path) and passes all the file names/paths by const reference to avoid some copies.
=> Small file fix and optimisation

32blit-stm32/Src/32blit.c, 32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp
Got tired of taking photos of the device, so added a screenshot button to the menu. Also restores rendering the firmware behind the menu since I moved the button handling recently.
Screenshots are saved with a new method added to `Surface` that saves the contents to an uncompressed .bmp file. I've tested it with RGB/paletted images. ~230k for a hires screenshot.
=> Screenshots

docs/Tools.md
Corrected variable name in Tools.md, and clarified that the documentation does apply to the new tool and that it's only really the installation that the 32blit-tools repo talks about (for now anyway).
Feels like a ridiculously small PR, but every time I look at it, the fact the sprite data variable name is wrong bugs me :-)
=> Minor documentation tweak

32blit-stm32/CMakeLists.txt, CMakeLists.txt
Makes the firmware build ~9.6k smaller. I was getting quite close to the limit when adding USB host code...
(The startup file is moved to the top of the source list as otherwise GCC optimises out all of the interrupt handlers...)
=> Enable LTO for 32blit-stm32

docs/Emscripten.md
Added note to include 32BLIT_PATH in cmake, in the Emscripten build instructions so that template-based projects build.
=> Another tiny documentation tweak

32blit/graphics/blend.cpp
This is just the `blend-fast-alpha` branch with two minor fixes. Tested a few examples and nothing looked broken.
Reduces the render time in my emulator by ~1.7ms. Before this, clearing the screen took nearly 4x as long as actually drawing anything...
=> Faster blends/fills (not mine)

32blit/audio/audio.cpp, 32blit/audio/audio.hpp
Avoid using 64bit ints for most of `get_audio_frame` removing ~1.6k of code. Also adjust the clipping by 1 so that it optimises down to a single instruction.
=> Audio optimisations

32blit/graphics/blend.cpp
Fixes the left edge of this circle https://daft-freak.github.io/32blit-beta/examples/shell.html?app=tween-test. Also hflipped blits I think (at least shmup looks less broken).
=> Small blend/fill fixes

32blit-stm32/STM32H750VBTx.ld
Useful for appending data post-build. (Like I did with my emulator)
=> Define a symbol for the end of (used) flash

docs/Linux.md, docs/Tools.md, docs/Windows-WSL.md, docs/macOS.md
Adds installing the tools to the OS-specific pages (except Windows/VS, which doesn't currently cover installing Python). Also adds some basic instructions on how to use the packer when ~duplicating build confi~ using a VS project.
=> Tweak docs for installing tools

32blit/graphics/surface.hpp, 32blit/graphics/text.cpp, examples/text/text.cpp
Use the surface clip rect instead. Removes the default clipping from the `Rect` version of `text` but makes it more consistent with the rest of the API. (Somehow missed the surface clip when adding this...)
=> Remove clip param to Surface::text

.travis.yml
... and update to the latest release. Includes switching to the "upstream" backend, which seems to build a bit faster (~2 mins on travis). Also should include the workaround for audio.
Bonus: flight and the `perspective` effect in tilemap-test now work (#97/#340). (The nans/infs are still there, they just don't cause exceptions any more...)
=> Switch to official Emscripten Docker image

.travis.yml, 32blit-sdl/Renderer.cpp, 32blit/doxygen.conf, site/examples/index.html, site/examples/shell.html
Pushes the Emscripten compiled examples to pages, also includes the API docs as they're currently the content of https://pimoroni.github.io/32blit-beta/ (also it was easy). May want to add `on: tags` at some point.
(The accelerated renderer commit is here mostly because WebGL is currently refusing to work in my Firefox...)
=> Deploy Emscripten examples

docs/32Blit-Firmware.md, docs/32Blit-Loader.md, docs/32blit.md, docs/ChromeOS.md, docs/Linux.md, docs/Tools.md, docs/VSCode.md, docs/Windows-VisualStudio.md, docs/Windows-WSL.md, docs/macOS.md, mingw.toolchain
Instructions for installing SDL2_image.dll and other dev files for MinGW WSL build. Plus support for copying SDL2_image.dll added to the cmake toolchain file.
Perhaps the SDL2 compile instructions should be substituted for a precompiled binary package and a bootstrap script to do all of this automagically.
=> Support SDL2_image in WSL/MinGw + docs

examples/tilemap-test/tilemap-test.cpp
Apparently `x % 0` is undefined behaviour.
=> Fix zero division error in tilemap-test betamax

32blit/graphics/primitive.cpp
This makes the width match the height (and also matches what the original unfilled algorithm would do). It does mean that the circle size is actually r * 2 + 1 though...
Result:
Should fix #31
=> Increase width of circles by one

examples/hardware-test/hardware-test.cpp
Adds a circle to indicate the expected joystick range.
Adds history, allowing joystick motion to be visualised.
Known: Joystick should effectively outline the circle, but seems to fall about 1px short from the bottom edge. I think this is a visual bug (looking at the joystick X/Y numbers) with either the dot plotting or the circle.
=> Add joystick history and range to hardware-test

32blit/audio/audio.cpp
Title says all, really.
The noise waveform was severely offset and not scaled to the full range of the channel, it looked typoriffic so it was presumably either that or a merge fail somewhere. Either way it's *technically* correct now and doesn't seem to break the ocean noise in Scrolly Tile.
Also switched to using `blit::random()` instead of `rand()` so it should be... uh... more random?
We should probably look into using a LFSR for noise predictability across platforms, perhaps?
=> Correct noise waveform for #351

32blit/graphics/surface.cpp
Went a step further than the `log2f` patch, this one is two instructions (on ARM). Saves nearly 3k of flash. Also clamps the minimum bit size to 1, which fixes images with one colour.
(Wasn't sure where to put the helper function, so just threw it at the top of the file)
=> Replace double-precision logs in packed sprite load

32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, 32blit.cmake, CMakeLists.txt
And avoid building it entirely in external projects. Unneeded since we're not linking it into games any more.
=> Drop the second HAL build

32blit-sdl/Input.cpp
Having to stretch over to Y was getting annoying while testing something today... Fixes #39.
=> Remap SDL Y button to x and add alternative mappings

32blit/graphics/surface.cpp
The else branch in `load_from_packed` had the same issues that were fixed in #282.
=> Fix sprite unpacking to RGBA

32blit-stm32/Src/32blit.cpp
Saved a few bytes here, used a few bytes there, all in all a net positive! Or negative. Depending on which way you tilt your blit.
=> Refine LIS3DH/MSA301 Normal/Beta auto-detection, fix accel polarity

32blit-stm32/Src/32blit.cpp, 32blit-stm32/startup_user.cpp, 32blit/engine/api_private.hpp
Found this while rebasing all my branches yesterday, wasn't included with the initial error handling PR due to depending on user-only.
Intended to catch abort and do something more useful than hang in an infinite loop, `exit` working is an err... undocumented bonus feature.
=> Reset to firmware on abort/exit

32blit-stm32/Src/gpio.cpp
Take advantage of the fact that `HAL_GPIO_Init` can setup multiple pins at once to save a few hundred bytes (`gpio::init` ends up as one of the largest non-HAL functions). Had this one lying around for a while as I can't decide if the LTDC bit is too messy.
=> Reduce calls to init_pin

32blit/graphics/sprite.cpp
Validate the header before attempting to load. Only checks for `SPRITEPK` as `SPRITERW` isn't handled anywhere.
=> Check packed_image header

32blit-sdl/CMakeLists.txt, 32blit-stm32/Inc/executable.hpp, 32blit-stm32/STM32H750VBTx.ld, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/main.c, 32blit-stm32/executable.cmake, 32blit-stm32/startup_user.s, firmware/CMakeLists.txt, firmware/firmware.cpp, firmware/firmware.hpp, firmware/metadata.cpp, firmware/metadata.hpp
Changes for listing games in flash and using the game metadata. Also some cleanup stuff. Has a few unfinished bits:
- ~Doesn't unload metadata when a game has none~
- A block is a 64k flash sector, could be anywhere down to 4k with subsector erases
- The CMake function for metadata only detects changes on the yaml, not the images
- ~There's a TODO in there for skipping to the end of a game while scanning flash~
- ~After you flash a game from the SD, it has two identical entries in the list~
- No RGB splash handling (tool doesn't generate them (yet?))
=> Flash game listing and metadata handling

32blit-stm32/Src/usbd_storage_if.c
No more slightly confusing "STM Product" device in my disk list. Other fields may also want updating.
=> Rename storage product from "Product"

32blit/audio/audio.cpp
This sets up a crude custom linear feedback shift register to produce psuedo random numbers of the noise waveform.
Should be consistent across platforms, fast and - most importantly - wont trample blit::random() in an interrupt and cause games using it to freeze.
=> Change audio random noise generator to LFSR

32blit/graphics/surface.cpp
Should be faster due to less offset calcs and calls to `bbf`. Probably more optimisations to do around here... I just kept noticing this one.
=> Draw sprites a line at a time in sprite_blit

firmware/firmware.cpp
Switch out the sort function for the file list and save ~800 bytes.
=> Smaller sort function

32blit-stm32/Src/32blit.cpp, 32blit/graphics/surface.hpp
A bunch of changes to reduce the size of `blit_menu_render`, which was larger than the firmware's `render`... (-~460 bytes)
And a little tidying.
=> Menu cleanup

32blit-stm32/executable.cmake, 32blit.cmake, docs/32Blit-Firmware.md
Removes the need to do a local build before a device build... Attempted to update the docs, `docs/32Blit-Loader.md` will need updated/replaced...
=> Use python tool for .flash targets

32blit-stm32/executable.cmake
Small issue with the tool: if you have neither defined, it won't generate the .cmake file and the build fails due to a missing include.
=> Trigger re-link on icon/splash updates

firmware/firmware.cpp
Included in #388 and #396, ignore if either of those get merged first.
=> Fix offset calc in scan_flash

firmware/firmware.cpp, firmware/firmware.hpp
Small cleanup/fixes and adds two new commands to the firmware:
- `__LS` - lists games in flash (returns offset and size (uint32), then metadata for each game)
- `ERSE[32bit offset]` - erases game at an offset
(`__LS` already existed, but all it did was reload the file list)
WIP for the tools:
```diff
diff --git a/src/ttblit/tool/flasher.py b/src/ttblit/tool/flasher.py
index 053106c..530ac28 100644
--- a/src/ttblit/tool/flasher.py
+++ b/src/ttblit/tool/flasher.py
@@ -1,5 +1,6 @@
import logging
import pathlib
+import struct
import time
import serial.tools.list_ports
@@ -28,6 +29,8 @@ class Flasher(Tool):
self.op_flash.add_argument('--file', type=pathlib.Path, required=True, help='File to flash')
self.op_delete = operations.add_parser('delete', help='Delete a game/file from your 32Blit')
+ …
```
=> Firmware list/erase commands

32blit-stm32/Src/32blit.cpp, 32blit/engine/menu.hpp
Reworks the firmware menu into a basic reusable menu class and adds scrolling and customisation options. Also changes the menu appearance a bit:
Customised menu from my emulator:
And even the file browser:
Usage example:
```c++
class MyMenu final : public Menu {
public:
MyMenu() : Menu("Title", item_data, 2) {
// optionally replace some pens/layout
}
// optionally render_item/update_item for more customisation
void item_activated(const Item &item) override {
// do things
}
Item item_data[2]{
{0, "Item 1"},
{1, "Item 2"}
};
};
MyMenu menu;
...
menu.update(time);
...
menu.render();
```
All the base class does is display a scrollable list of items that you can sellect with A.
Has (possibly a lot of) overlap with #216. I think that one does a more in the common menu class. (Sub …
=> Menu refactor

darwin.toolchain, docs/macOS.md
Pretty sure this is unneeded as building for macOS on a mac isn't cross-compiling and it works fine on mine (CMake defaults to clang anyway)...
=> Remove darwin toolchain

32blit/engine/engine.cpp
This avoids the blend functions from the firmware being used in user code, which are slightly slower due to optimisation level differences. The fact that `set_screen_mode` resets most of `screen` should probably be documented somewhere... (it already did that)
I only noticed this due to drawing not being any faster in a release build...
=> Avoid copying entire screen surface in set_screen_mode

.vscode/cmake-kits.json
This makes the toolchain automatically appear as a kit in VS Code (still needs the manual config in the docs for out of tree projects)
=> Add VS Code CMake tools config

32blit/engine/file.cpp
Makes sure that the leading slash is stripped after doing something like `add_buffer_file("/file", ...)`. Also fixes `list_files("dir/")` not working for buffer files.
=> Improve slash handling for buffer files in list_files

32blit/graphics/sprite.cpp, 32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp, firmware/metadata.cpp
Reverts `byte_count` back to how it was originally (before I broke it), handles a 0-size palette as a full 256 colours and changes the packed image format a bit to allow larger images.
Also, handles loading unpacked images, adjusts `Surface::load` to be more consistent with `SpriteSheet::load` and adds a helper to use an unpacked image without loading it into ram...
Requires https://github.com/pimoroni/32blit-tools/pull/32 for breaking changes to `packed_image` format.
=> Packed image/surface improvements

32blit/engine/file.cpp
"the the" -> "to the"
Looks like I copy/pasted that a few times... Oops.
=> Fix repeated typo in file docs

32blit-sdl/CMakeLists.txt
Added 32BLIT_SDL_TITLE value, to allow projects to override the default "CMake!" window title.
=> Make SDL window title settable

32blit-sdl/File.cpp, 32blit-sdl/Input.cpp, 32blit-sdl/Renderer.cpp, 32blit/engine/profiler.cpp, 32blit/engine/profiler.hpp, 32blit/graphics/text.cpp, 32blit/types/map.cpp, examples/hardware-test/hardware-test.cpp, examples/matrix-test/matrix-test.cpp, examples/platformer/platformer.cpp, examples/profiler-test/profiler-test.cpp, examples/serial-debug/serial-debug.cpp, examples/tilemap-test/tilemap-test.cpp, firmware/firmware.cpp
This fixes most of the non-"converting X to Y" warnings in VS. (With [this slightly nasty patch](https://github.com/Daft-Freak/32blit-beta/commit/98b07a02e62509190030230f3f10f65a3e358b28), there are two in the tool).
=> VS warning fixes

32blit-sdl/CMakeLists.txt, docs/Windows-VisualStudio.md
Since I keep saying this is easy, I thought I should check that it actually works... which it nearly did. Just a little tweak to SDL detection needed... I think this is easier than having to edit the current .sln to point to the right place...
Definitely no VS files here:
With that many warnings, it has to be a VS build :smile:
Bonus: Also works in VS 2017.
=> VS + CMake out-of-tree build docs

32blit/engine/timer.cpp, 32blit/engine/timer.hpp, 32blit/engine/tweening.cpp, 32blit/engine/tweening.hpp, 32blit/types/map.cpp, 32blit/types/map.hpp
Some functions in 32blit have defaults declared in their `.cpp` instead of `.hpp`, which pretty much renders them invisible.
First noticed it playing with Tweens (which are, by the way, awesome), then found other instances, in Timers and Maps.
=> Defaults fix

32blit-stm32/Src/main.c, firmware/firmware.cpp
Free up some memory as API calls still allocate from the firmware heap. (I noticed that opening too many files at once would cause a crash, still doesn't work as there's a limit of 2 in fatfs but returns an error instead of crashing)
=> Free metadata before launching games

32blit-sdl/CMakeLists.txt
Should build, won't package the libraries though. (That would need something like https://github.com/Daft-Freak/32blit-beta/commit/647d0fe1cd4eac77bfe3709305d186ae089b5fb8, which ended up [failing with permission errors when I tried it](https://github.com/Daft-Freak/32blit-beta/runs/1412024010?check_suite_focus=true) )
=> Unbreak non-framework macOS builds

firmware/firmware.cpp
=> Hide folders beginning with '.' in the firmware menu

32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/main.c
Broken in 71195ae as that check happens after the firmware has done the switch.
(Though somehow still seemed to work sometimes...)
=> Fix HOME+reset and crash reset

.github/workflows/cmake.yml, .gitignore, 32blit-stm32/CMakeLists.txt, 32blit-stm32/Inc/executable.hpp, 32blit-stm32/STM32H750VBTx.ld, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/executable.cmake, 32blit-stm32/startup_user.s, 32blit.toolchain, 32blit/CMakeLists.txt, firmware/firmware.cpp, firmware/firmware.hpp, firmware/metadata.cpp, firmware/metadata.hpp, stdlib/build-libstdc++, stdlib/build-newlib, tools/gather-relocs
The last part is finally here...
1. Custom PIC/non-PIC newlib/libstdc++ builds (currently based on the versions from the 7.3 toolchain, build scripts in `stdlib/`)
2. Toolchain automatically downloads and extracts these
3. Games are built with PIC flags linked against the PIC libraries, firmware uses the non-PIC libs.
4. Games have a prepended "RELO" header, containing offsets to patch (GOT, init/fini arrays, data relocations) (currently `tools/gather-relocs`)
5. At flash time (from SD or over CDC) the relocation header is parsed and skipped, the flash offset is applied as we go
6. Many games at once!
A few relatively minor issues remain:
- CDC flashing doesn't check if the game is already there. (SD flashing uses the checksum + name)
- ~`gather-relocs` and the metadata tool don't work …
=> WIP: PIC for games

.github/workflows/cmake.yml, 32blit-sdl/CMakeLists.txt, vs/sdl/sdl2-config.cmake
Rather than assuming the user has read the docs, this update to `sdl2-config.cmake` will auto-fetch the required SDL2 libraries for a Visual Studio CMake build when first configured.
If the user already has an `include` directory, it will do nothing.
May not be totally robust and catch all edge cases, and also does things outside of the build dir (which is potentially really bad) so:
TODO: suggestions for making this a better CMake citizen.
=> Make sdl2-config.cmake auto-fetch libraries

32blit-stm32/Src/quadspi.c, firmware/firmware.cpp
Found this while tidying up my branches, mostly stolen from d968941. Flashing DOOM goes from 18s -> 10s on my slow card.
=> Faster flashing from SD

examples/matrix-test/matrix-test.cpp
By "fixing" the sign conversion warning here, I turned it into an infinite loop. (Which would read out of bounds by a few billion).
Replace the reverse loop with a reverse iterator.
=> Fix matrix-test crash

examples/palette-swap/palette-swap.cpp
For who knows what reason I'd opted to pick the width/height of the spritesheet out of the raw packed sprite buffer, rather than use `screen.sprites->bounds`. That- as you might expect- eventually broke. This fix brings back our lovely ships by giving them a non-zero width.
=> Fix silly broken hack to get sprite size

32blit.cmake
Checks the 32blit tools are at least `BLIT_MINIMUM_TOOLS_VERSION` and outputs some slightly refined help text for installing/updating tools.
=> Patch tools version check

32blit/audio/mp3-stream.cpp, 32blit/audio/mp3-stream.hpp, site/examples/index.html
Switches the sample position to unsigned to avoid `(stream.get_current_sample() * 1000) / 22050` wrapping to negative at the `* 1000`.
=> Fix time going negative in the MP3 example

32blit.toolchain, docs/Linux.md
Check that the download/unzip succeeded, always do the download (it exits early if the file exists with the expected hash) and move the EXISTS check to the extracted files. Still not the most helpful message if `unzip` isn't installed. "No such file or directory"
=> Improve stdlibs download/unzip

32blit-stm32/Src/display.cpp
fixed bug in dma2d_hires_flip(). It is 0x0001 instead of 0x0000 for RGB888 type. Privous one will copy extra 1/4 memroy out of range.
DMA2D function for hires_pal mode was added. I think it would be even better if we use dma2d for color mode transform in lut mode. It will avoid the ltdc mode changes and lut copy operation.
=> Update dma2d_hires_pal_flip() function, fixed bug in dma2d_hires_flip()

32blit-sdl/CMakeLists.txt, 32blit-stm32/executable.cmake, 32blit.toolchain
Adds a status output to the SDL and STM32 executables, since I just notice CMake had a long, quiet period of contemplating during which it wasn't obvious what on earth it was doing. This is just a gentle affirmation to users that Something Is Happening.
I have also tweaked the `stdlib.zip` download message, frustratingly recreating some of the logic that `file` uses to avoid spamming the message repeatedly during the build process.
=> Patch cmake to make moar noise

32blit/graphics/blend.cpp, 32blit/graphics/sprite.cpp, 32blit/graphics/sprite.hpp, 32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp, 32blit/graphics/tilemap.cpp, 32blit/graphics/tilemap.hpp, 32blit/types/vec2.cpp, 32blit/types/vec2.hpp
Unless I'm missing some case this is _less_ efficient than passing by value... Probably only by a few instructions. Shaves about 300 bytes off Babble. (Lots of calls to `sprite`)
This charge was a find/replace of `const (u?int[12368]+_t|int|float) &` -> `$1 `
=> Avoid passing basic types by reference

32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-sdl/JPEG.cpp, 32blit-sdl/JPEG.hpp, 32blit-sdl/System.cpp, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Inc/jpeg.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/file.cpp, 32blit-stm32/Src/jpeg.cpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp, 32blit/engine/save.cpp, 32blit/graphics/jpeg.cpp, 32blit/graphics/jpeg.hpp, firmware/firmware.cpp
This started as me discovering that calling `list_files` repeatedly would kill the firmware. This was because the data for the `vector` containing the file list was allocated from one heap, and deallocated from the other (well, it _attempted_ to do that, nothing actually gets deallocated...). `get_save_path` had a similar issue.
Since this is already breaking the API, this also adds `blit::is_storage_available`, cleans up `decode_jpeg_file` a bit and merges the two "debug" functions (`debugf` also gets float support by doing the formatting outside of the firmware).
=> Fix some nasty leaks from the API + other API changes

32blit-stm32/Inc/USBManager.h, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/file.cpp, 32blit-stm32/Src/main.c, 32blit/engine/menu.hpp, firmware/firmware.cpp
Moves mass storage mode enabling to the menu... which was easier said than done. Split from #450.
Adds "Storage Mode" to the menu, with the current status on the right. Since this means that it con now be enabled _anywhere_, also add some checks to prevent enabling storage while files are open... and the other way around.
I haven't tested the auto-disable on eject yet (still broken on my Ubuntu, Windows laptop a bit dead...)
=> Mass storage menu rework

firmware/firmware.cpp
When flashing from the SD card:
- check for flashed games with the same author/title
- overwrite if the same or greater size (in blocks)
- delete it otherwise and flash as normal
When flashing through CDC
- flash as before
- clean up old copies afterwards
Also, track free space between games and fix a few bugs. Some of this is a little inefficient, will be easier to fix when the launcher is a separate thing.
=> Prevent duplicate games

32blit/types/vec2.hpp
Currently if you do `Point(1)` what that actually does is `Point(Vec2(float(1), 0.0f))` which is... unexpected. Make the `Vec2` constructor that takes one/two floats `explicit` to avoid that.
There are probably more constructors that could be marked explicit, but I've hit this one a few times.
=> Make Vec2(float, float) explicit

32blit-stm32/Inc/main.h, 32blit-stm32/Inc/tim.h, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/main.c, 32blit-stm32/Src/stm32h7xx_it.c, 32blit-stm32/Src/tim.c
Dims the system LED using the solution as explained by @zenodante in #464
Avoids extra timer setup, but - let's say deliberately - does not support any fancy fading LED effects.
System LED states are limited to 3bit colour, or 8 possible states:
* Black, White
* Red, Green, Blue
* Teal, Purple, Yellow
Right now:
* Red = Discharging
* Green = Fully Charged
* Blue = Fast Charging
* Purple = Pre-charge
* Yellow = ?? (Maybe battery low?)
* Teal = ?? (Busy status for system actions?)
* Black = Your blit is probably off or in DFU mode =D
* White = ??
=> Dim LED using SysTick_Handler

32blit/graphics/sprite.cpp, 32blit/graphics/surface.cpp
Adds a new `SPRITERL` format which is an RLE version of the packed format. The tool falls back to `SPRITEPK` if the result is larger.
Size difference on most of the default assets/metadata + the spritesheet from my game:
```
tunnel                          18678    7755    -10923
gadgetoid_raycaster             19474    9756     -9718
flight                          10386    1279     -9107
s4m_ur4i_space_shooter_ships    10386    4544     -5842
s4m_ur4i_space_shooter_backdrop 10386    4597     -5789
s4m_ur4i_top_down_shooter       10374    5268     -5106
no_image                         6206    1289     -4917
s4m_ur4i_pirate_tilemap         10386    6778     -3608
s4m_ur4i_dingbads               12438    9000     -3438
babblesheet                      3250     754     -2496 …
```
=> Run length encoded packed sprites

32blit-sdl/CMakeLists.txt, 32blit-stm32/Src/32blit.cpp, 32blit/engine/file.cpp, firmware/firmware.cpp
- Avoid a conflict if a game contains a `metadata.cpp` (launcher hits this)
- Delete unused variables and a function from `32blit.cpp`.
- Fix the progress bar for CDC flashing. (started at the flash offset instead of 0)
- Include the size when using `list_files` on "buffer" files
=> Misc fixes from the "launch" branch

firmware/firmware.cpp
I must have tested this with a file that fit exactly. Another case of a single character breaking everything...
=> Fix free space check

docs/32Blit-Firmware.md
I have changed my PC since I last developed for 32blit (different laptop, newer Windows version), and to my surprise the device was not recognized in DFU mode. I don't recall if I needed to do this driver update last time, but since now I had to, decided to add info about it to the documentation.
=> Added information if DFU mode device does not show up in Windows

32blit-stm32/executable.cmake, firmware-update/CMakeLists.txt
`TARGET_FILE_BASE_NAME` requires CMake 3.15, we only require 3.8 and debian buster only has 3.13. It's only used for building the updater and the output filename only matters in releases so fallback to the old way if it's not available.
=> Fix building with older CMake

32blit-sdl/CMakeLists.txt
Tested with a clean configure and no vcpkg.
=> Really REALLY fix Windows SDL dll copy

32blit-stm32/Src/32blit.cpp
If I hold down the MENU button for a long time in the main menu, it will queue an exit event, even if the user code is not running. Upon launching the next game, it will auto-quit right away, because the flag was set to terminate. 
Fixed it by adding a check to see if user code is running before flipping the flag.
=> Fixed: holding the menu button will not queue exit event if user code was not running

32blit-stm32/Inc/32blit.h, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/file.cpp, 32blit/engine/api_private.hpp, 32blit/engine/file.cpp, firmware/firmware.cpp, launcher-shared/dialog.hpp, launcher/launcher.cpp
- Removes some now unneeded flash scanning and metadata parsing from the firmware (saving near 3k, mostly from dropping image unpacking)
- Fixes a few minor bugs (including A/B being backwards on the dialogs)
- Brings back deleting games from flash (`api.erase_game`)
- Makes part of the save handling reusable for getting the metadata of whatever is running
=> Fixes/cleanups for the firmware 

32blit-stm32/Src/32blit.cpp
Defers the switch in/out of the system menu into the main loop, rather than the interrupt where - potentially - strange things could happen.
=> Don't toggle system menu in interrupt

firmware-update/CMakeLists.txt
This should make sure that the embedded firmware is regenerated whenever the firmware changes.
=> Fix the dependency between the firmware updater and the firmware

launcher/launcher.cpp
In this PR, I've stopped showing hidden files (beginning with `.`) and prevented interaction (play with A, delete with Y) on the "no games found" screen.
=> Prevent interaction with invalid games

32blit/engine/tweening.cpp
As mentioned in [this issue](https://github.com/pimoroni/32blit-beta/issues/506), tweens don't set a default value when you `start()` them (or rather, it defaults to 0.0f regardless of the tweening range).
This will force the value to start at `from` when starting the tween.
=> Set value to <from> when a tween is started

32blit/graphics/sprite.cpp, examples/sprite-test/sprite-test.cpp
Title says it all. Right now the blit functions just bail if `surface.sprites` is a `nullptr`, should probably return some sort of error status (via int return or some errno horror) so that the Lua bindings can detect and report a failure. (Even if C++ can't get that fancy)
=> nullptr check surface.sprites, plus more comprehensive sprite-test

32blit/graphics/tilemap.cpp, 32blit/graphics/tilemap.hpp, 32blit/types/point.hpp, 32blit/types/rect.hpp, 32blit/types/size.hpp, 32blit/types/vec2.hpp, 32blit/types/vec3.cpp, 32blit/types/vec3.hpp
Was attempting to use TileMap for something and forgot about the restriction on the bounds. `constexpr` patch allows doing stuff like
```c++
constexpr blit::Size bg_size(64, 32);
uint8_t bg_tiles[bgSize.w * bgSize.h];
```
Also noticed that the transform flags for TileMap don't match the ones for sprites (horizontal flip and x/y swap are swapped)... (didn't change that here)
=> Misc tilemap-related changes

32blit-stm32/Src/display.cpp
Have checked this doesn't horribly explode anything or lose a column from the *left* hand edge (thanks, bug in Doom Fire).
Probably need a bit of a de-magic-numbering on the LTDC config since it's pretty heinous.
I spent far too long tweaking the front/back porch values - missing the off by one error in the LTDC layer config - and I'm pretty sure some of them might not be entirely aligned with the typical values in the datasheet. Changing them doesn't seem to do all that much, though.
=> Bring back missing col 319

docs/Windows-WSL.md
Adjust the WSL docs a bit based on some recent questions/comments on Discord.
- Move the MinGW warnings down to when we start talking about MinGW
- Split the package lists for MinGW/ARM
- Update toolchain install to be clearer that you don't need any 3rd party packages on Ubuntu 20.04
=> Update WSL docs a bit

32blit/engine/timer.cpp
Proposed Fix #512 
TimerCallback is now executed after t->started set for infinite timers, or after timer has transitioned to FINISHED state for non infinite timers.
This allows the timer callback function to change timer params and restart the timer without it immediately transitioning to FINISHED.
This could be a breaking change for other developers.
=> Feature/fix 512 - Moved location of TimerCallback execution.

32blit-stm32/Inc/display.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/display.cpp
Now we don't need to use need_render / framebuff busy / dma2d busy three signal in controlling. Only one need_render signal! And current setup could avoid any waste in cpu time in flip operation. 
Sorry I need to modified the file one by one in web page. The git cli to github in China is really slow :(
=> Rearrange the signals in render process

32blit-stm32/Src/SystemMenu/about_menu.cpp
For @lenardg :smile: (Okay, I had a rough idea how to do this and had to do it before I forgot...)
Displays if there is an SD card inserted and if it is, the free/total space (in megabytes). Will also display "not mounted" if it was detected but failed to mount.
=> Display SD card status and free space in the about menu

32blit-sdl/System.cpp, 32blit-stm32/Inc/persistence.h, 32blit-stm32/Src/32blit.cpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp, 32blit/engine/engine.hpp, firmware/firmware.cpp, launcher-shared/CMakeLists.txt, launcher-shared/executable.hpp, launcher-shared/metadata.cpp, launcher-shared/metadata.hpp, launcher/launcher.cpp
Some more stuff related to #435. Adds parsing for the extra metadata from https://github.com/32blit/32blit-tools/pull/51 and support for using a flashed .blit to launch files.
Will conflict with multiplayer as also touching API. Small TODO: use argv for SDL launch path.
Slightly patched emulator I tested with:
[gameboy.zip](https://github.com/pimoroni/32blit-beta/files/5757356/gameboy.zip)
Changes were pretty much:
```c++
auto launchPath = blit::get_launch_path();
if(launchPath)
openROM(launchPath);
```
=> File associations/ extra metadata parsing

32blit/engine/engine.cpp, 32blit/engine/input.hpp
Apply change suggested in #477 by @Daft-Freak to make input less completely bonkers.
=> Fix input debounce/update rate

32blit-sdl/CMakeLists.txt
When installing on a Mac, copy `SDL2_net.framework` into the `Game.app/Contents/Frameworks` directory.
=> Fix SDL2_net.framework installation on Mac

32blit-sdl/CMakeLists.txt, docs/Linux.md, docs/Windows-VisualStudio.md, docs/Windows-WSL.md, docs/macOS.md
Update some docs and fixup the windows DLL copy. (I should really test that...)
Though macOS docs install SDL+friends through `brew`, while we use the frameworks for CI... May want to cover that in the docs too (since it's currently the easiest way to create a redistributable binary)
=> SDL_net related things

32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp
Adds SPRITERW support to `Surface::save` and BMP support to `Surface::load(filename)`. Also fixes loading non-paletted SPRITERW.
=> Surface load/save

32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, 32blit.toolchain, 32blit/CMakeLists.txt, launcher-shared/CMakeLists.txt
To make libraries work without needing to add the PIC flags manually. Also fixes undefined symbol errors due to linking the stdlibs in the wrong place.
=> Rework toolchain PIC handling

32blit-stm32/Src/32blit.cpp, firmware/firmware.cpp
First one makes sure the save path is for the current game, instead of the previous one in `init`. Fixes a bug where if you exited a game with saves, the launcher would load that as it's theme...
Second one prevents games launched from flash from getting whatever that least launch path was... or junk...
=> Small game launch related fixes

32blit.toolchain, docs/Windows-VisualStudio.md
Mentions adding a release config in the setup docs and adds some info about doing a cross-build (I've tested that this at least builds...). Had to patch the toolchain to work around the lack of `unzip` though.
(Maybe the boilerplate should have a CMakeSettings.json with a reasonable set of configs and placehholder paths?)
=> VS docs + VS cross-build

vs/examples/.gitignore
The VS build generates some assets for the _text_ example, that were not gitignored. Added a new gitignore file for the VS examples.
=> Added gitignore that ignores asset files for text example when compiled with VS

32blit-stm32/Src/display.cpp
Moves the mode update even later (after the next render), which better matches what I intended to do in the first place. (Not flip in the new mode until something was rendered in it).
Fixes doing a hires -> lores switch.
Also changes a bunch of whitespace since VS Code refuses to leave that alone now...
=> hires -> lores mode change fix

launcher/launcher.cpp
This really brings nothing to the table but showy effects. The launcher always felt a bit static to me, and I wondered how smoothly a basic background effect might run.
I've added `swoosh` and the launcher now renders 3 swooshes in the background which use out-of-phase sine waves with slightly varied scaling to give some interesting emergent patterns.
The scanline rendering isn't an optimization, the effect will run perfectly smoothly hitting all pixels... it's actually a sort-of-hack to dampen/stop the perception of horizontal movement which made the effect less subtle and more outright distracting.
=> Swooshy launcher background

firmware/firmware.cpp
Checks for `firmware-update.blit` at init and if found, flashes deletes and starts it. Then does the same for `launcher.blit`.
Also cleans up any old firmware updaters so you don't end up with a screen full of them...
=> Automatically install firmware/launcher updates

32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp, examples/flight/flight.cpp, launcher/launcher.cpp
Mostly discovered by all the random junk on my SD... First two are the most important, the other two just expand BMP support a little.
Not fixed:
- Having an image that doesn't fit in the static buffer on your SD card explodes.
- Paletted BMPs can't have alpha, which is not really a problem for screenshots, but the "alpha" field is written as 0 from most editors...
=> Misc BMP/screenshot/surface fixes

firmware/firmware.cpp
I was having an issue where running firmware-update-v0.1.8.blit, or `make firmware-update.flash` would jump my 32blit into a semi broken state.
I believe - when not launching `firmware-update.blit` from SD card - that the firmware updater was being deleted from flash before it had a chance to be run.
This patch changes that behaviour so old updates are only deleted when the reset_target is 0.
Users on v0.1.8 will have to copy `firmware-update.blit` to SD card and reset to update, either via `32blit firmware-update.blit` or just a file copy over MSD/direct onto the card.
=> Only delete old firmware when not launching something

firmware/firmware.cpp
This drops some code that was rendered obsolete by #545 and switches launcher identification from `title` to `category`.
If you want to write a custom launcher, it *must* have a category of "launcher". Subsequent to this change the title can be anything, so swapping in new launcher should be slightly easier.
We might need a special case for "launcher" type apps, expanding on the "delete old launcher" behaviour to *always* delete and replace a launcher when any other launcher is flashed. While it would be fine to have *multiple* launchers flashed at once, it would always be the first one in Flash that wins so it's a little redundant.
=> Assorted tweaks to firmware->launcher behaviour

32blit/graphics/surface.hpp, 32blit/types/rect.hpp, 32blit/types/size.hpp
Helpers and additional operator support on some basic types. Probably need to flesh this out a lot more, but I'm adding these as my sprite-editor code demands it because I hate repeating myself.
Is there any drawback to this?
Also strikes me that Pen should cast to a `uint32` and just do a direct comparison, but for love nor money I couldn't get the thing to cast. Maybe the compiler is clever enough to optimize my long-winded comparison. Maybe I should just be casting and comparing pens in my code?
=> Helpful things

32blit/graphics/surface.cpp, 32blit/types/size.hpp, launcher/launcher.cpp, launcher/launcher.hpp
Zoomed "view" somewhat sucks here, but I'd like to implement file association support so I can hijack 128x128 spritesheets and open them in the Sprite Editor. This is step 1.
=> Display 128x128 spritesheets (or other images) at correct aspect

firmware/firmware.cpp
Prevents random old stuff found after the launcher being used as the launcher.
=> Clear category if no BLITTYPE metadata

examples/scrolly-tile/metadata.yml, examples/scrolly-tile/scrolly-tile.cpp
Daft-Freak mentioned this a while ago, that highscore tracking would be cool.
This adds basic highscore tracking to scroll-tile (ignoring the level seed).
=> Added basic highscore tracking for scrolly-tile

32blit-stm32/Inc/stm32h7xx_hal_conf.h, 32blit-stm32/Src/main.c
Hasn't exploded.
Seems more accurate than HSI, at least comparing Super Mario Land vs the same emulator on a PC and a real GB is the same speed now. Most clocks are the same (I think?) ADC is 2MHz lower.
Not that I have any idea what I'm doing with these...
=> Use HSE as clock source

32blit-stm32/Inc/sound.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/sound.cpp, 32blit/engine/api_private.hpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp, firmware/firmware.cpp
Reserves some space at the end of flash for temporary files and adds some API for using it (only handles one file in there, could be improved).
```c++
File f("path/to/thing", OpenMode::read | OpenMode::cached);
// file has been copied to flash if possible
// cache space is reserved until close
```
Also, stops audio while ext flash is unavailable to prevent games using audio callbacks from crashing.
(WIP?, at least I don't feel like I've spent enough time on this...)
=> Flash tmp area/cache

32blit/engine/file.cpp
Apparently I didn't test the fallback/error handling... and my emulator hits both of these cases.
=> Fix flash cache fallback

32blit/types/rect.hpp
Minor enhancement, after I found myself writing code to get the middle of a Rect for the 42nd time.
=> Added center() function to blit::Rect

32blit-stm32/STM32H750VBTx.ld
Doesn't fix anything, but does prevent metadata overwriting ITCM if you attempt to use it. (Making that actually work for games is more work...)
=> Move flash_end to the right place

32blit/audio/audio.cpp, 32blit/audio/audio.hpp, 32blit/audio/mp3-stream.cpp, 32blit/audio/mp3-stream.hpp, examples/audio-wave/audio-wave.cpp
- Rename the callback for more consistency (#344)
- Pass the channel to the callback, helps if you're using more than one channel... and just makes sense
- Stop doing << 8 on samples. Now you can use 16-bit samples without reducing the volume 256x
- Make the callback optional to allow using a fixed pattern.
- `wave_callback_arg` is now a generic `user_data` pointer.
Changes for users are...
Old:
```c++
channels[0].wave_callback_arg = some_ptr;
channels[0].callback_waveBufferRefresh = &callback;
//...
void callback(void *data) {
//...
for(int i = 0; i < 64; i++)
channels[0].wave_buffer[i] = some_sample;
}
```
New:
```c++
channels[0].user_data = some_ptr;
channels[0].wave_buffer_callback = &callback;
//...
void callback(AudioChannel &channel) {
auto data = channel->user_data;
//...
for(int …
```
=> Rework audio wave channel

32blit-stm32/executable.cmake
Only possible to hit this if you're being lazy and doing:
```
cmake -G Ninja -B build -DCMAKE_TOOLCHAIN_FILE=~/repos/32blit-beta/32blit.toolchain
ninja -C build-test
```
Without doing `mkdir/cd`.
=> Fix metadata absolute path handling

firmware/firmware.hpp
Uses `screen.bounds` to resize the flash progress bar for 160x120 resolution.
I don't know how this will interact with palette-mode display buffers, but I'm guessing... poorly? Will test.
=> Support flash progress at 160x120 res

32blit-stm32/Inc/CDCDataStream.h, firmware/firmware.cpp
A result of trying to figure out why https://github.com/ali1234/32blit-webserial-test didn't work.
One problem was that it would end up stuck in the reloc parsing with 2 bytes in the buffer when it needed 4. This makes it so that you can return from StreamData with a few bytes in the buffer and they will be preserved on the next call.
Also deletes a bunch of stream stuff that we're not using.
=> CDC stream adjustment/cleanup

32blit-sdl/CMakeLists.txt, 32blit-sdl/File.cpp, 32blit-sdl/emscripten-shell.html, 32blit/engine/save.cpp
Fixes the the install step for Emscripten to install the actual game wasm/js instead of just the shell. Then adds a minimal custom shell and makes saves persist.
Includes a workaround for an old SDL issue I forgot to fix. (I'll probably merge [the fix](https://github.com/emscripten-ports/SDL2/pull/136) soon, but would still need to add a new tag/update Emscripten/wait for an Emscripten release/...)
The sync in the save code feels a bit like the wrong place, but `close_file` doesn't know if the file was used for writing... or if it was written to somewhere that needs syncing.
=> Emscripten install improvement and persistent saves

firmware/firmware.cpp, firmware/firmware.hpp
Adds a `LNCH` command which allows ~the device to serve lunch~ launching flies in the same way that the launcher does. Also sends back an OK at the end of flash/save.
This is working towards making auto-launch optional and work for files too. (Need to do some tool bits...)
=> Launch command

32blit-sdl/CMakeLists.txt
From
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/daftfreak/programs/32blit-beta/32blit-sdl/SDL2_NET_INCLUDE_DIR
used as include directory in directory /home/daftfreak/programs/32blit-beta/32blit-sdl
SDL2_NET_LIBRARY
linked by target "BlitHalSDL" in directory /home/daftfreak/programs/32blit-beta/32blit-sdl
-- Configuring incomplete, errors occurred!
```
to
```
CMake Error at 32blit-sdl/CMakeLists.txt:102 (message):
SDL_net not found!
-- Configuring incomplete, errors occurred!
```
Also, fails a lot faster instead of waiting until the end.
=> More helpful errors for missing libs

32blit-stm32/Src/32blit.cpp
Tried to play 32blox with the stick. Same thing would probably happen if a game was entirely accel based...
=> Fix "sleep" if the stick is the only thing being used

32blit/audio/mp3-stream.cpp, 32blit/graphics/primitive.cpp, 32blit/graphics/surface.cpp
Fixes a few warnings that show up with the boilerplate's extra warning flags.
(Mostly clean with https://github.com/Daft-Freak/32blit-boilerplate/commit/26afd314b77ac630b345f4eb3bd24dbf6829b282)
=> Warning fixes - -Wextra edition

32blit-sdl/Main.cpp
This is useful for testing multiplayer games, as you can run two
copies with arbitrary window positions.
=> Add a command line option to set the position of the SDL window

32blit-sdl/CMakeLists.txt
This doesn't seem to explode any more and results in boilerplate-based builds including the SDL libs (using brew to install).
`fixup_bundle` could also be used to handle copying all needed dlls for Windows... but that's currently not working for a bunch of other reasons... (Mostly path related *sigh*)
=> Install libraries into mac bundle when not using frameworks

examples/jpeg/metadata.yml, examples/mp3/metadata.yml, examples/raycaster/metadata.yml, examples/text/metadata.yml, examples/tween-demo/metadata.yml
Improves... this:
Also changes the one example that uses "Pimoroni" instead of "pimoroni".
=> More metadata author consistency

.github/workflows/cmake.yml
Avoid using the repo name in paths so that actions builds don't fail if your repo has a different name.
(Guess who hasn't renamed their 32blit-beta repo :smile: )
=> Actions repo name fix

32blit/audio/audio.cpp
Adjust the LFSR tap so that 0x8000 doesn't end up always 0 and fix the overflow check to actually happen on overflow. Without this frequency doesn't have much of an effect and some values result in no sound at all.
(The waveform isn't off-centre now and it... sounds better? :shrug: )
=> Adjust NOISE waveform

32blit-stm32/Src/SystemMenu/about_menu.cpp, 32blit-stm32/Src/SystemMenu/battery_menu.cpp, 32blit-stm32/Src/SystemMenu/connectivity_menu.cpp
Another patch I found in my giant pile of branches. Saves a little RAM.
(I have a another patch that makes all the USB descriptors const too https://github.com/Daft-Freak/32blit-beta/commit/b5494a36202c954ce55f4c6a3ff6e770d9b09455 which removes most of the firmware's `.data`)
=> Make most menu item lists const

32blit-sdl/Input.cpp, 32blit-sdl/Input.hpp, 32blit-sdl/Main.cpp, 32blit-sdl/Renderer.cpp, 32blit-sdl/Renderer.hpp
I realised that you can pretty easily get access to SDL events in a game with something like:
```c++
#ifndef TARGET_32BLIT_HW
#include <SDL.h>
int sdl_event_watch(void *user_data, SDL_Event *event) {
switch(event->type) {
//...
}
return 1;
}
#endif
void init() {
//...
#ifndef TARGET_32BLIT_HW
SDL_AddEventWatch(sdl_event_watch, nullptr);
#endif
}
```
So, I attempted to do something with the mouse... coords were all wrong due to the scaling. Then I realised that _almost_ all the scaling stuff could be replaced with `SDL_RenderSetLogicalSize`/`SDL_RenderSetIntegerScale`, which also scales input. (The `Stretch` mode is a bit nasty, I'm just overriding the scale every resize... but only the `KeepPixels` mode is actually used.)
=> Rework SDL scaling

launcher/launcher.cpp, launcher/launcher.hpp, vs/launcher/launcher.vcxproj
Allows the launcher to list more associated files (tested to about 700-800), with the side effect that it will now crash on a larger directory even if the files aren't associated.
(Without pre-reserving the vector, the exponential growth causes it to run out of memory part way through the loop. Using https://github.com/Daft-Freak/32blit-beta/commit/6ae6dba6397d508d0586ae058f6756fa2f1b8ae7 to actually detect out of memory.)
=> Handle more files in the launcher without crashing

32blit-sdl/Multiplayer.cpp, 32blit-stm32/Inc/multiplayer.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/SystemMenu/about_menu.cpp, 32blit-stm32/Src/SystemMenu/battery_menu.cpp, 32blit-stm32/Src/SystemMenu/connectivity_menu.cpp, 32blit-stm32/Src/multiplayer.cpp
This allows SDL to receive messages faster than one every 20ms(#597) and adds a handshake to the STM32 backend so that `is_multiplayer_connected` actually means that two devices are connected and in "multiplayer mode" (#598).
=> Multiplayer improvements

examples/sprite-test/sprite-test.cpp
Added a `screen.sprite` example using the scale options.
=> Sprite scale example

32blit-stm32/executable.cmake, firmware/firmware.cpp
Removes the auto-launch after flashing something through CDC. However, if the flashed file is a launcher we still have to run it as we probably just deleted the running one... (Similar thing for firmware-updates)
=> No auto-launch on CDC flash

32blit-sdl/CMakeLists.txt, 32blit-sdl/DefaultMetadata.cpp, 32blit-sdl/System.cpp, 32blit-sdl/UserCode.hpp, 32blit-stm32/Src/32blit.cpp, 32blit/engine/api_private.hpp, 32blit/engine/version.cpp, 32blit/engine/version.hpp
Adds an API that allows games to get their metadata at runtime (just the strings, as those are already in both builds). Requires https://github.com/32blit/32blit-tools/pull/73 for SDL url/category to not be blank.
=> Get metadata API

README.md, docs/VSCode.md, docs/Windows.md
This is the thing I keep mentioning whenever a Windows user has setup problems... Finally got around to working out what was required. This was tested on a "clean" Windows VM.
The basic Windows instructions are now very similar to the Linux/macOS setup. I was tempted to replace every occurrence of `make x` in the docs with `cmake --build . --target x` since that works with every CMake generator. (Instead of "follow these docs, but use nmake instead of make")
I guess the "you need a cross-compile env" bits in 32blit.md and 32blit-firmware.md could link to this too.
(Apparently the default windows Python install has `py` in PATH and not `python` or `python3`...)
=> Document Windows builds without needing WSL or a full Visual Studio install

32blit-stm32/startup_user.cpp, 32blit/engine/api_private.hpp
Should be avoided, but handling it instead of crashing is probably still a good idea. Also, it's not like we were going to need 4 billion API versions...
version_major = breaking changes
version_minor = non-breaking API additions.
=> Split api_version to handle breaking changes

32blit-sdl/CMakeLists.txt, mingw.toolchain
If SDL2_DIR didn't have a trailing slash some of the find_*s would fail, resulting in MinGW not copying some of the dlls.
The MinGW toolchain defaults SDL2_DIR to something without a trailing slash...
=> Fix MinGW SDL DLLs

32blit/graphics/surface.cpp, 32blit/types/point.hpp, 32blit/types/size.hpp, 32blit/types/vec3.cpp
First one fixes `vec.transform(Mat4::identity())` having an effect. Second one makes it so you can do:
```c++
static constexpr blit::Size size{96, 96};
uint8_t data[size.area()];
blit::Surface surface{data, blit::PixelFormat::P, size};
```
(From my minimap code)
There are probably a lot more methods that could be `const`/`constexpr`.
=> A few small fixes

32blit/types/point.hpp, 32blit/types/rect.hpp
For usefulness and consistency's sake.
The code appears to include random trailing whitespace which `whitespace-cleanup-mode` in Emacs automatically zaps..
=> Implement == and != operators for Point and Rect

32blit-sdl/CMakeLists.txt
I just exploded my build a bit...
Another case of needing to do a bit more work because the magic command that fixes it was only added "recently".
(This only works if `metadata.cmake` has its quotes escaped... which it doesn't.)
=> Handle metadata with quotes in 32blit-sdl

32blit-sdl/VideoCapture.cpp
This stops ffmpeg spamming MPEG related errors at me. (Yes, I'm actually using the video recording stuff...)
=> Use .mp4 for video extension

32blit/graphics/blend.cpp, 32blit/graphics/tilemap.cpp, 32blit/graphics/tilemap.hpp
Reduces "Super Blit Kart" `render` times by 8ms and makes the track rendering > 2.5x faster. First commit also means you can put something in the tile index you have defined as empty for other uses.
(I also have some patches for sprite stretch blits, but I think those need more work/testing)
=> Tilemap optimisations

32blit-sdl/Multiplayer.cpp, 32blit-sdl/Multiplayer.hpp, 32blit-stm32/Inc/CDCCommandStream.h, 32blit-stm32/Inc/CDCDataStream.h, 32blit-stm32/Src/CDCCommandStream.cpp, 32blit-stm32/Src/multiplayer.cpp
Fixes for SDL connection handling and easier bridging to the STM32 side.
Fun test I came up with for this (assuming no --connect/--listen):
- Start game 1. Starts listening.
- Start game 2. Connects to 1, 1 stops listening.
- Start game 3. Starts listening.
- Start game 4. Connects to 3, 3 stops listening.
- You now have two independent pairs of games open.
- Close 3. 4 disconnects.
- Close 2. 1 starts listening, 4 connects to 1, 1 stops listening again.
- Still have a connection, but neither of the ones we started with!
=> More multiplayer improvements

32blit/audio/mp3-stream.cpp, 32blit/audio/mp3-stream.hpp, examples/mp3/mp3.cpp
Adds a `restart` method to `MP3Stream` (resets decoder to start) and `loop`/`from_start` flags to `play`.
=> MP3 looping and restart/play from start

32blit-sdl/Multiplayer.cpp
... the one thing I didn't test with the last multiplayer PR was _not_ using multiplayer. This should stop the SDL code from attempting to (re-)connect even if multiplayer is disabled. Also improves a bit of the error handling.
=> Minor SDL multiplayer fixes

32blit/engine/engine.cpp, 32blit/engine/engine.hpp
I keep `#include`-ing api_private.hpp to use `get_us_timer` for profiling. This adds a `blit::now_us` wrapper for when you just want to time one thing precisely without setting up the profiler.
(Sometimes isn't any more precise than a millisecond... *looks at Emscripten/Firefox*)
=> Add a wrapper for the microsecond timer

32blit/audio/mp3-stream.cpp, 32blit/audio/mp3-stream.hpp
~22k -> ~4.7k.
Avoid the file buffer if unneeded (buffer files) and reduce the size of the output buffer (can't remember why it was so big).
Just need to test more on device...
=> Waste less memory on buffers in MP3Stream

firmware/firmware.cpp
Tries to fix #631 but has its own drawbacks.
Still crashes after about 45 game flashes, but ensures the launcher list is re-loaded immediately after the flash and avoids listing a game that has been deleted.
=> Patch launcher reset after flash

32blit/graphics/blend.cpp
Mostly opening this for the first patch, which un-breaks screenshots after I got the alpha channel backwards somehow.
Second patch just avoids some work for alpha == 0 (which ends up as 1 after the "fast" `alpha` function). 
Third is for bugs in `RGBA_RGBA` that were pointed out recently.
=> Misc blend changes

32blit/audio/mp3-stream.cpp
Smaller buffer exposed some existing bugs. Fixes an underrun right at the end of the file preventing the end from being detected and the decode loop using the worst-case output size instead of calculating it, resulting in half-filled buffers most of the time.
(Guess that was why the buffers were so big...)
=> Some MP3 buffering fixes

32blit-stm32/startup_user.cpp, firmware-update/CMakeLists.txt
Because of the bug in <0.1.11 where the API version was uninitialised, the latest firmware updater doesn't run... unless you already have that firmware. (Also makes sense for any future unavoidable breaking changes.)
The updater doesn't even use almost all of the API anyway. (`buttons` from `blit::tick` and `set_screen_mode` from the init code. `set_screen_mode` is also the first function)
Tested that this runs all the way back to v0.1.2 (first version with .blit). (Excluding any other issues, like the one that deletes the updater)
=> Ignore API versioning in the firmware updater

32blit/graphics/tilemap.cpp, 32blit/graphics/tilemap.hpp
Now have only one implementation of offset(), and the version that takes a blit::Point is actually callable.
=> Made offset(Point) callable, reduced function redundancy!

launcher/launcher.cpp
Shows the framerate in milliseconds using a bargraph (1ms = 1 dot) and the frame time in microseconds.
Enter the credits screen and press Y to toggle.
Fixes a couple of instances where the background swooshes were tanking framerate unnecessarily:
* Behind the credits screen
* Behind the screenshot browser
There's no real reason to include a frame time meter in the launcher (edit: except it's a critical part of the 32blit UX so it's probably a good idea to stay on top of anything that might be tanking the framerate), so I'm flagging this TODO: maybe find a way to make this a system feature so we don't have to copypasta it into every darn game.
=> Add toggleable frame-time meter to launcher

32blit/graphics/tilemap.cpp, 32blit/graphics/tilemap.hpp
Clamps to the tile at the edge of the map. Almost called it `CLAMP` but `NONE`/`DEFAULT_FILL` also clamp (hmm, kind of like `CLAMP_TO_BORDER` in most graphics APIs).
Though while doing this, noticed that `DEFAULT_FILL` doesn't do what I expected it to do (`default_tile_id` is an index into the map instead of the tileset...)
Also, enum case inconsistency...
=> Add a CLAMP_TO_EDGE repeat mode to TileMap

.editorconfig
Corrupting patches when you save them is more than a little annoying. Especially when you're using  `git add –patch` and trying to edit...
=> Don't trim whitespace from patches

README.md, docs/Linux.md, docs/Windows-WSL.md, docs/Windows.md, docs/macOS.md
Main improvement is prioritising the "generic" Windows setup over the VS one, as it covers all the dependencies. This makes the OS setup docs all cover the same thing: installing dependencies and command-line builds.
Also more specific Linux requirements and not listing "building" under "prerequisites" in most of the docs.
=> More docs improvements

32blit-sdl/Main.cpp, 32blit-sdl/System.cpp, 32blit-sdl/UserCode.hpp
Added a command line option to SDL builds to make it easier to test Blits that handle file associations; returns the provided file from the `get_launch_path()` function as it does when launching an associated file on the 32blit itself.
TL;DR - saw the `// TODO` comment, and did :-)
=> Added --launch_path option to SDL builds

32blit-stm32/Inc/32blit.h, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/CDCCommandStream.cpp, 32blit-stm32/Src/SystemMenu/about_menu.cpp, 32blit-stm32/Src/SystemMenu/battery_menu.cpp, 32blit-stm32/Src/SystemMenu/connectivity_menu.cpp, 32blit-stm32/Src/SystemMenu/firmware_menu.cpp, 32blit-stm32/Src/SystemMenu/system_menu_controller.cpp, 32blit-stm32/Src/adc.c, 32blit-stm32/Src/display.cpp, 32blit-stm32/Src/fatfs_sd.c, 32blit-stm32/Src/i2c.c, 32blit-stm32/Src/jpeg.cpp, 32blit-stm32/Src/main.c, 32blit-stm32/Src/multiplayer.cpp, 32blit-stm32/Src/quadspi.c, 32blit-stm32/Src/sound.cpp, 32blit-stm32/Src/spi.c, 32blit-stm32/Src/tim.c, 32blit-stm32/Src/usbd_conf.c, 32blit-stm32/Src/usbh_conf.c, 32blit.toolchain, 32blit/engine/engine.cpp, 32blit/engine/engine.hpp, firmware/firmware.cpp, launcher/launcher.cpp
Noticed some of these while doing other stuff and a lot more after finding that the toolchain had `-Wno-unused-variable` set.
Last commit fixes the initial flash of uninitialised data after being powered off (by clearing LTDC ram when `persist` needs reset). It does add a warning about writing out of bounds that I can't seem to avoid.
=> Mostly cleanup patches

32blit-stm32/Src/32blit.cpp
Since `update` isn't getting called you end up with broken audio most of the time (unless you're streaming entirely in the callback). I _think_ this shouldn't break the other user of `sound::enabled` ("user code" disabling for flash stuff)
=> Disable sound when the menu is open

32blit-stm32/Src/32blit.cpp, firmware/firmware.cpp
First two commits improve firmware updates (would show the "no launcher" screen while cleaning up). The rest avoid resetting while launching a game (restoring the behaviour before the launcher split) and exiting a game (a TODO since the firmware split).
(Bug fixed by the last commit only exists with #652 + this)
=> Less resets for launcher/game switching

32blit-stm32/Src/display.cpp
It was 321x241. Also calculates the accumulated values to be more clear.
(Found while experimenting with a Pico connected to the LCD connector...)
=> Fix LTDC active area

docs/Windows-VisualStudio.md
VS adds some overrides that break the build... Didn't spot that when I wrote this section. Another way to fix this would be to include a mostly-configured `CMakeSettings.json` in the boilerplate.
Still possibly not the most reliable config as it depends on VS shipping a compatible toolchain...
=> Fix the VS device build

32blit.toolchain
CMake finds most of these for us as part of its compiler detection(https://github.com/Kitware/CMake/blob/v3.16.9/Modules/CMakeFindBinUtils.cmake#L112). Using find_program for the other two avoids a mix of full paths and names in the cache. 
Which helps if there's weird stuff going on with PATH... *looks at VS*
=> Fix some paths

32blit.toolchain
Toolchain used `NONPIC_STDLIBS`, CMakeLists used `NOPIC_STDLIBS`, resulting in the firmware using the system libraries. If you're using Ubuntu these are similar enough that this doesn't explode.
=> Link the firmware against the right stdlibs

32blit/engine/timer.hpp, 32blit/engine/tweening.hpp
This is used by 32blit-lua to store the Lua state and callback function reference.
=> Add user_data field for Timer

docs/Linux.md, docs/Windows-WSL.md
Small fix for an older issue. (#287)
This is only a "recommends" in Debian stable/Ubuntu LTS so may not get installed automatically.
(Didn't do anything about `sudo pip` as I'm a little against that...)
=> Add python3-setuptools to apt line

examples/logo/logo.cpp
This reverts commit 725a7ee1071687f9337e09bec2397d48e7153066.
Not sure how that got there.
=> Remove test code from logo example

firmware/firmware.cpp
Fixes flashing something with file associations while it's running. (It would try to launch the old one the next time you opened a file)
I was trying to avoid work by only setting the launcher offset instead of this... resulting in this fun corner-case.
=> Do a full scan_flash before launching after flash

docs/Linux.md
Remove separate install of construct/bitstring since these are required by the tools anyway.
Add line continuations to the apt install command to make it clear it's *one* command.
Add a troubleshooting section detailing a quick fix for pip3 complaints about PATH.
=> Update Linux docs

.github/workflows/Emscripten.yml
Should fix the "unexpected hash" errors caused by https://dl.bintray.com/homebrew/mirror/jpeg-9c.tar.gz returning "Forbidden!" again...
TODO: boilerplate too
=> Bump Emscripten version

32blit-config.cmake, 32blit-sdl/CMakeLists.txt, 32blit-stm32/executable.cmake
If the tool does fail we'll either fail to include the generated file on the next line, or ignore the error and continue using stale config.
Error you get without this if metadata/assets.yml is missing:
```
...
FileNotFoundError: [Errno 2] No such file or directory: '/batt/repos/.../metadata.yml'
CMake Error at /batt/32blit/32blit-stm32/executable.cmake:60 (include):
include could not find load file:
/batt/repos/.../build/metadata.cmake
Call Stack (most recent call first):
CMakeLists.txt:6 (blit_metadata)
```
=> Check that calling the tools didn't fail

32blit/graphics/surface.cpp
It's possible that there's enough padding at the end of the data to encode an extra 0 entry if `bits_per_pixel` is < 7... and one of my sprites in blit kart happens to cause that.
Might be possible to trigger something similar with non-RLE packed data too, but haven't checked.
(Probably wouldn't have caught this if I didn't have ASan enabled!)
```
=================================================================
==579178==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62900009a200 at pc 0x555fd9cef633 bp 0x7faffb824ba0 sp 0x7faffb824b90
WRITE of size 1 at 0x62900009a200 thread T3 (Loop)
#0 0x555fd9cef632 in blit::Surface::load_from_packed(blit::File&, unsigned char*, unsigned long, bool) /home/daftfreak/programs/32blit-beta/32blit/graphics/surface.cpp:710
#1 0x555fd9ce6548 in …
```
=> Fix corner-case off-by-one in RLE sprite unpacking

32blit-stm32/Inc/32blit_battery.hpp, 32blit-stm32/Inc/i2c-bq24295.h, 32blit-stm32/Src/32blit/32blit_i2c.cpp, 32blit-stm32/Src/i2c-bq24295.c
Attempting to read the fault register and the status register in one read would result in the fault register always reading as 0. We're still not doing anything with the fault status, but at least it reads correctly now.
Also some cleanup.
=> Rix reading battery fault status

32blit/graphics/blend.cpp
Makes `Surface::transparent_index` actually do something. Always uses the value from the dest surface, though I guess P->P blits don't make sense if both don't use the same palette anyway.
=> Use transparent_index

32blit-stm32/Src/32blit.cpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp
This avoids the issue where if you open the menu for a while and close it the game appears to hang/skip forward as it gets a huge number of `update` calls. (The same thing could happen to the menu, but it doesn't do much in update so was a lot harder to notice)
Also skips "menu time" for timers/tweens (tested with tween-demo). Didn't increase the API version despite adding a new field as nothing breaks with a mismatch (may sometimes trigger the skip code incorrectly, but only once and at the start of the game where it wouldn't call `update` anyway).
(This has been broken since 0b260b43b7ab37067746d9cbc8764734d67535ff)
=> Skip time spent with the menu open

32blit-config.cmake, 32blit-stm32/Middlewares/ST/STM32_USB_Host_Library/Class/CDC/Src/usbh_cdc.c, 32blit/graphics/color.cpp, 32blit/graphics/primitive.cpp, CMakeLists.txt, examples/logo/logo.cpp, examples/particle/particle.cpp
An assortment of patches from the pico branch that aren't really pico related.
- A few example changes
- Small optimisations that are more noticeable on the pico (saves ~20ms in `hsv_to_rgb` there, the examples that do that per-pixel are still slow though)
- Half-working CDC host with TinyUSB-based device (will connect and receive, sending from the host hangs though.)
=> Non-pico patches from the pico branch

32blit-sdl/System.cpp
Oops.
Happened to notice while ~~completely breaking~~ tweaking "the cupboard".
=> Fix SDL get_metadata description

32blit-stm32/Src/SystemMenu/firmware_menu.cpp, 32blit/engine/menu.hpp
If the running executable category is "launcher" this will hide the "Exit Game" menu item, since we're not in a game anyway.
Additionally moves SystemMenu from "32blit-stm32" to "firmware" where it belongs. (Though, to be fair, the line between the HAL and the firmware is... hazy)
=> Remove "Exit Game" from fw menu in Launcher

32blit-sdl/emscripten-shell.html
Avoids blurriness with hidpi screens. The shell used for the example browser already did this. (Specified twice for browser support reasons)
=> Set image-rendering on Emscripten canvas

32blit-pico/st7789.cpp
Switches to manufacturer supplied gamma settings, which are clearly better with more brightness/contrast.
Turns on content-adaptive brightness, which seems to give a significant boost in display brightness. May need testing with various games to see if there are any artifacts or drawbacks - other than potential additional power usage - of using this feature.
=> pico: Tweak ST7789 gamma and content-adaptive brightness

32blit-pico/config.h, 32blit-pico/input.cpp, 32blit-pico/led.cpp, 32blit-pico/main.cpp, 32blit-pico/storage.cpp, docs/pico.md
Just some minor stuff. binary info stuff results in:
```
picotool info -a ./hardware-test.uf2 
File ./hardware-test.uf2:
Program Information
name:            Hardware Test
version:         v1.0.0
web site:        https://github.com/32blit/32blit-sdk
description:     A test of 32Blit's inputs and outputs.
features:        UART stdin / stdout
binary start:    0x10000000
binary end:      0x10019914
embedded drive:  0x10c00000-0x11000000 (4096K): 32Blit
Fixed Pin Information
0:   UART0 TX
1:   UART0 RX
13:  Green LED
14:  Red LED
15:  Blue LED
16:  Y Button
17:  X Button
18:  A Button
19:  B Button
20:  DOWN Button
21:  RIGHT Button
22:  LEFT Button
23:  UP Button
Build Information
sdk version:       1.2.0
pico_board:        pimoroni_picosystem
build date:        Aug 22 2021
build attributes: …
```
=> Pico tweaks

pico.toolchain
For consistency with 32blit.toolchain. More importantly, this makes the command in the boilerplate/docs actually work.
=> Set 32BLIT_DIR in the Pico toolchain too

32blit-stm32/Src/SystemMenu/connectivity_menu.cpp
Refuse to enter storage mode with "No SD Card" instead of getting stuck at "initialising".
(Seems unmounting on Ubuntu is broken again though)
=> Improve feedback for trying to use storage mode with no SD card

32blit-pico/main.cpp, 32blit-sdl/Renderer.cpp, 32blit-sdl/Renderer.hpp, 32blit-sdl/System.cpp, 32blit-sdl/System.hpp, 32blit-stm32/Inc/display.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/display.cpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp, 32blit/engine/engine.hpp
I thought about it too much and had to write it... cleanup based on an old patch, 565 bits loosely based on the other PR.
The main thing this adds is: `bool set_screen_mode(ScreenMode new_mode, PixelFormat format)`, which enables:
- Paletted `lores` mode on non-pico (doesn't reconfigure LTDC like `hires`, just changes the input format to the doubling magic)
- RGB565 modes on non-pico
- Returns false instead of just ignoring you on non-supported modes/formats (so everything except 565 on pico)
- The API function this uses could easily be extended to allow things like passing in a framebuffer pointer
This does increase the API minor version, so games built with this won't run on older firmware (but old games will be fine).
[Updated screen mode …
=> Screen mode cleanup and extended API

32blit/graphics/sprite.cpp, 32blit/graphics/sprite.hpp, 32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp, examples/shmup/shmup.cpp
This is hopefully just some cleanup of `Surface` methods. It replaces  `(stretch_)blit_sprite` with new `(stretch_)blit` overloads that take a surface/transform and removes the optional `hflip` param from `blit()` (the new overloads allow a full transform).
There are deprecated wrappers to avoid breaking old code, though only one of the three functions was used in one example... and there only seems to be one repo on GitHub that uses the sprite blit functions directly (DANG).
=> Blit function consistency shuffle

32blit-sdl/CMakeLists.txt
Avoids a CMake error when you have multiple targets with metadata in the same CMakeLists/subdir.
=> Prepend target name to generated metadata.cpp

32blit-sdl/Input.cpp, 32blit-sdl/Input.hpp, 32blit-sdl/Main.cpp, 32blit-sdl/System.cpp
This is a first shot at having the game controllers which can rumble react to blit::vibration in the SDL port.
=> Introducing game controller rumble in SDL builds

32blit/types/map.cpp
mipmap_index is an unsigned integer so checking it for lesser than 0 has no effect
=> Fix mipmap boundary check

32blit/graphics/tilemap.hpp
These were supposed to be different flags. Probably unnoticed as the default is both and I use neither in blit kart.
=> Fix load_tmx flags typo

32blit-sdl/File.cpp
Removes an Emscripten workaround (I fixed it in SDL and we're already using a version with the fix) and makes save paths work everywhere instead of just `open_file`.
Which would be really handy if someone wanted to add a `remove_save` wrapper :smile:
=> SDL file path fixes

32blit-pico/file.cpp, 32blit-stm32/Src/file.cpp
`blit::list_files` has been leaking a whole 56 bytes... for the last two years... This fixes it by just putting the `DIR` object on the stack instead.
(I wasn't even doing blit stuff, just came to uh, "borrow" some of the fatfs glue)
=> Fix DIR leak in blit::list_files

32blit-stm32/Src/32blit.cpp
`exit` is marked as not returning, bad things happen if it does. This worked fine until #661 made it so that `blit_exit` didn't reset when there wasn't an error.
This is the easiest fix of always resetting in `blit_exit`... which isn't as clean an exit as you get from using the menu. While typing this patch I thought of an alternative, which is slightly more magic: https://github.com/Daft-Freak/32blit-beta/commit/645a3a504e8c92328e9811363937cfbdc5ae7758
=> Fix exit(0) crashing

32blit-sdl/System.cpp
Allows changing the screen size by altering one place (in System.hpp).
=> Avoid hardcoding the screen size for SDL everywhere

32blit-pico/main.cpp
We could end up missing frames if `update` doesn't take much time.
Fixes an empty `update`/`render` sometimes missing frames in `hires` and improves `logo` modified to use `hires` mode to get a constant 25 FPS instead of sometimes falling to ~16 (it also has an empty `update`).
=> pico: Don't sleep when we need to render

docs/Windows.md
Setting up a new Windows install... everything still seems to work here, except things have moved a bit.
Using the latest Arm tools mostly works as well, but the firmware fails to link...
```
[ 95%] Linking CXX executable firmware.elf
AR10B2~1.EXE: error: ´╗┐CMakeFiles/firmware.dir/firmware.cpp.obj: No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\GNUARM~1\102021~1.10\bin\AR10B2~1.EXE' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```
=> Update Windows setup docs for VS2022

docs/pico.md
Just some small tweaks
- ~half of ITCMRAM is reserved (though none of it was usable before)
- vgaboard has a bit less RAM available
- HID code for vgaboard isn't merged, but does support the joystick
(There's also unmerged SD card support for vgaboard, but it's a huge pile of code...)
I should probably finish some of the "make VGA actually usable" bits.
=> Misc pico docs fixes

32blit-pico/CMakeLists.txt, 32blit-pico/config.h, 32blit-pico/display.cpp, 32blit-pico/display.hpp, 32blit-pico/main.cpp, 32blit-pico/st7789.cpp, 32blit-pico/st7789.pio
This is mostly moving code and a bit of deduplication. (Which I've been avoiding doing to not cause rebase pain for my "everything pico" branch)
Oh, and shaved two instructions off the PIO program...
=> Pico display cleanup

firmware/firmware.cpp
Found another case of not updating the game list... could result in duplicate games or not flashing new versions.
=> Rescan flash after flashing from SD

32blit-stm32/Src/quadspi.c
Example code:
```c
*(volatile uint8_t *)0x91FFFFE0; // boom, system gone
```
Locks up _everything_ including debugging...
Guess who spent most of the day debugging this :neutral_face:. (Not that I need those bytes, it was just a really weird crash to hit)
More info: https://www.st.com/resource/en/errata_sheet/es0396-stm32h750xb-and-stm32h753xi-device-limitations-stmicroelectronics.pdf#%5B%7B%22num%22%3A90%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C67%2C546%2Cnull%5D
=> stm32: work around QSPI failing to read the last 32 bytes

examples/platformer/CMakeLists.txt, examples/tilt/CMakeLists.txt
This disables the tilt example (doesn't do anything interesting) and sets `ALLOW_HIRES=0` for platformer. Both of these would fail to build with a 320x240 display.
=> Pico examples changes

32blit-pico/audio.cpp
Nothing uses this by default, but I've had the patch lying around for months...
=> pico: "Fix" PWM audio clock div

32blit/engine/file.cpp, 32blit/engine/file.hpp, launcher/launcher.cpp
Mostly to avoid DaftBoy running out of memory while listing the root of my SD card... but seems useful for the launcher too.
=> Add optional support for filtering in list_files

launcher/launcher.cpp
*Immediately adds a warning back after cleaning most of them up* :facepalm: :laughing: 
The reduced warning noise made this easy to spot. Thought this was a bug, but the original user of this just got moved elsewhere.
=> Fix unused variable in launcher

.github/workflows/cmake.yml, 32blit-sdl/CMakeLists.txt, ci/install_sdl_macos.sh, ci/install_sdl_mingw.sh, ci/install_sdl_vs.sh, docs/Windows-VisualStudio.md, docs/Windows-WSL.md, vs/sdl/README.md, vs/sdl/sdl2-config.cmake
This started as an attempt to work around build failures on macOS, then turned into "I wonder if I can clean this up by updating"... and then resulted in [android boilerplate for some reason](https://github.com/32blit/32blit-boilerplate/compare/main...Daft-Freak:32blit-boilerplate:android).
First three are fixes and could be split if we just want fixes for now. Then, macOS/Windows (VS+MinGW) SDL versions are updated which allows some simplification as they both support `find_package` now. 
There's some cleanup to make macOS frameworks slightly less special, the VS script doesn't create two copies of the headers/libs and the MinGW script no longer needs to patch the config.
2c89fb106a779b80e258e75108b3433bf379d609 and 96a175fa266e25e1ca613bd2ee1ca79fa443a599 allow [including SDL sources …
=> Update to latest SDL for macOS/Windows builds

32blit-stm32/Src/32blit.cpp
The previous check was unreliable, it's still possible we were called from user code when it's disabled (launch from SD will disable user code to flash before calling this).
Replace the check with a bool set around calling tick, which should always be accurate. (Unless someone attempts to launch from `render`...)
This reliably crashed my blithub downloader, but doesn't seem to break the launcher even though it should...
=> Fix delayed game switch

32blit-stm32/Inc/32blit.h, 32blit-stm32/Inc/32blit/i2c.hpp, 32blit-stm32/Inc/CDCCommandStream.h, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/32blit/i2c.cpp, 32blit-stm32/Src/CDCCommandStream.cpp, 32blit/engine/api_private.hpp
A bit similar to #261. Allows inserting I2C transfers into the I2C state machine. Should probably bump the API version for this... Also has a few small cleanups.
Useful if you want to do something crazy like add a Pico W for wifi things. Mostly PR-ing this since the code exists and works.
=> User I2C support v2

.github/workflows/Emscripten.yml, .github/workflows/Visual Studio.yml, .github/workflows/cmake.yml
Fixes these:
(repeat for other builds)
... except for one warning left on the Emscripten build.
Boilerplate: https://github.com/32blit/32blit-boilerplate/pull/25
=> Update actions for deprecation warnings

firmware/firmware.cpp, firmware/firmware.hpp, launcher-shared/dialog.hpp, launcher/launcher.cpp
First half: fixes some issues with failed flashes. Second half: use file size from headers instead of the actual file size.
- Fixes a crash when flashing a .blit fails
- Prevents overwriting things stored at the start of flash when running low on space (or trying to flash something unreasonably big)
- Simplifies size calc a little and is consistent with the size used after the file is flashed
A side effect of this is that you can append extra data to the end of a .blit and the flashing code ignores it (at least when loading from the SD card). Previously it would get flashed, but would likely get another .blit flashed on top of it later.
=> Minor firmware blit flashing improvements

32blit-sdl/File.cpp
Here's an easy one. Avoids errors at the end of reading files.
=> sdl: don't return error when reading 0 bytes

32blit-pico/CMakeLists.txt, 32blit-pico/display.cpp, 32blit-pico/display.hpp, 32blit-pico/main.cpp, 32blit-pico/storage.cpp
Various scanvideo changes (some quite old):
- Moves scanline updates to core1 (more reliable timing)
- Fixes sync
- Partial `hires` support (can only have one mode, defaults to `lores`, `ALLOW_HIRES=1` switches to `hires`)
Last commit is a bit of a hack, but I used it to port DaftBoy. VGA still isn't very useful without the input stuff...
=> pico: scanvideo improvements

32blit-sdl/System.cpp, 32blit-sdl/System.hpp
This fixes the fact that SDL only called `tick` every 20ms, so you would always be running behind and get two updates. Also switches `render`/`tick` around as SDL was backwards compared to STM32/Pico.
=> Adjust SDL loop timing a bit

docs/Linux.md
After #788, 11/12 should work. 7.x wasn't tested and even debian stable has 8.x now.
=> Update GCC version in linux docs

32blit-stm32/executable.cmake
Adds a lot of noise to build output for information that isn't useful most of the time. (`size` providing most of the useful info)
Leaving the .hex output, which is also of questionable usefulness...
=> stm32: remove readelf from post build commands

32blit-sdl/CMakeLists.txt
Default stack was decreased in https://github.com/emscripten-core/emscripten/commit/157fcd4650161d9e0261966e2d3b529d62e1babc. 64k results in screen corruption in even the most minimal example, 256k is enough to fix this but increase to 1MB to be safe. (Old default was 5MB)
Also clean up to use the preferred `-sTHING=` syntax and remove the `EXTRA_` from `EXPORTED_RUNTIME_METHODS`.
=> Increase Emscripten stack size (+options update)

docs/Emscripten.md
This bit me when I was testing #792 - hopefully splitting the configure and build steps, and decorating the step with a :warning:  will make it more obvious.
=> docs: Make emscripten path warning more obvious.

32blit-pico/CMakeLists.txt
The blit SDK itself is not affected by this as it includes the pico-sdk import in the root CMakeLists. Anything using the toolchain file (like the boilerplate) is a bit broken.
Prevents errors like:
```
[cmake] CMake Error at /home/daftfreak/workspace/pico/pico-sdk/tools/CMakeLists.txt:61 (find_package):
[cmake]   find_package called with invalid argument ".."
[cmake] Call Stack (most recent call first):
[cmake]   /home/daftfreak/workspace/pico/pico-sdk/src/rp2_common.cmake:47 (pico_add_uf2_output)
[cmake]   32blit-pico/CMakeLists.txt:140 (pico_add_extra_outputs)
[cmake]   32blit-pico/CMakeLists.txt:148 (blit_executable_int_flash)
```
=> Fix builds using pico.toochain with SDK 1.5.0

32blit.cmake, 32blit/32blit.hpp, 32blit/graphics/sprite.cpp, 32blit/graphics/sprite.hpp, 32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp, 32blit/graphics/tilemap.hpp, launcher-shared/metadata.cpp
The least old thing here is the blit wrappers (nov 2021)
=> Remove deprecated compatibility wrapper

launcher/launcher.cpp
Saves the path of the last file to be launched and scrolls the file/folder lists back there when restarting the launcher. Also used the same font for the folder list as the file list... and a few minor things.
I think we used to have this back before the launcher was a separate thing, and it was annoying me recently. (Trying to test a big list of blits)
=> Remember launched item in launcher + font changes

.github/workflows/Emscripten.yml, .github/workflows/cmake.yml
I instinctively went for the artifacts to try and test some changes on a PR and found there were none :cry: 
This PR should fix that!
=> CI: Upload install results as artifacts.

examples/hardware-test/CMakeLists.txt, examples/picosystem-hardware-test/CMakeLists.txt
Running it on non-picosystem things can result in some brokenness due to the GPIO stuff. (Make me think I've broken VGA more than once...)
=> Only build picosystem hardware test for picosystem

firmware/firmware.cpp
"32blit flash launcher.blit" has never been a valid command. It would have once been "32blit flash save --file launcher.blit" but that is now deprecated in favour of "32blit install launcher.blit".
=> Fix the message displayed when no launcher is installed

firmware/firmware.cpp
This prevents a crash when QSPI tries to read past the end of flash as a result of a bad serial command. 
There's also a patch waiting for the tools to stop it from doing that.
=> Firmware: reject erase commands beyond the end of external flash

32blit-pico/CMakeLists.txt, 32blit-pico/main.cpp
Seems appropriate, but requires latest pico-sdk.
Also saves 2.5k RAM.
=> pico: use pico_rand for random API

32blit-pico/CMakeLists.txt
Adds some flags to the BlitEngine library as the pico sdk does not set things globally. Also switches to nano stdlibs, mostly to avoid exceptions related code getting pulled in through libstdc++.
Saves ~24k of flash for the logo example and some RAM too.
The enabled policy requires CMake 3.13, but the pico-sdk requires that itself.
=> Pico build size improvements

32blit-stm32/startup_user.s
Point it to `do_init` (the closest thing to a game's entry point)
=> stm32: "fix" the Reset_Handler warning

32blit-pico/CMakeLists.txt
Port two commits that were missed in the pico port. This does highlight that the first half of `blit_metadata` is identical between the three copies of it...
=> Sync some blit_metadata changes to 32blit-pico

32blit/types/point.hpp
For `int32_t`. rect/size.hpp already do this.
=> include cstdint in point.hpp

32blit-pico/CMakeLists.txt, 32blit-pico/board/vgaboard/config.cmake, 32blit-pico/input_usb_hid.cpp, 32blit-pico/tusb_config.h, 32blit-pico/usb.cpp, 32blit-pico/usb.hpp, 32blit-pico/usb_descriptors.c, 32blit-pico/usb_device.cpp, 32blit-pico/usb_host.cpp
(Opening this so I don't keep forgetting about it)
USB HID based input for VGA. Draft because I only tested it on three controllers (one of them doesn't work for some reason). Could use some testing on some "common" gamepads (but not xbox stuff as they don't do HID... *sigh*)
What does work is flashing [this uf2 to a PicoSystem](https://github.com/32blit/32blit-sdk/files/8813671/picosystem-gamepad.zip)
Edit: Patch to hardware-test for testing https://github.com/Daft-Freak/32blit-beta/commit/48650294b5a65d4208b9f50ed4e2a0ccc70a4047
=> pico: HID input

32blit-config.cmake, 32blit-pico/CMakeLists.txt, 32blit-sdl/CMakeLists.txt, 32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, firmware/CMakeLists.txt
Basically this replaces `blit_executable_int_flash(name crc.cpp)` with `blit_executable(name INTERNAL_FLASH src.cpp)` but also:
- makes it work for external projects
- allows overriding the default with `-DBLIT_EXECUTABLE_INTERNAL_FLASH=`
- removes the sdl/pico stubs
(Somewhat inspired by `add_executable(WIN32/MACOSX_BUNDLE)` ... and needing a similar thing for pico standalone/loader builds)
=> blit_executable(_int_flash) improvements

32blit-pico/CMakeLists.txt, 32blit-pico/main.cpp, 32blit-pico/multiplayer.cpp, 32blit-pico/multiplayer.hpp, 32blit-pico/tusb_config.h, 32blit-pico/usb.hpp, 32blit-pico/usb_device.cpp, 32blit-pico/usb_host.cpp
Another few patches from the pile, from when I was trying multiplayer with every combination of blit <-> pico.
Requires enabling `CFG_TUH_HUB` to use multiplayer and input at the same time on the vga board. (Which uses quite a bit more RAM...)
Also a step towards handling the flash command for the (very) WIP pico launcher
=> pico: usb host multiplayer

32blit.toolchain
If we were re-downloading the stdlibs because the hash changed, we wouldn't extract it later because the dir already existed.
I only noticed this because my build script was failing to link everything after a system upgrade. (That is _after_ working around the python annoyingness with the tools...)
=> Delete old stdlibs files when redownloading

32blit-sdl/Main.cpp
Everything is already automatically scaled by the renderer. Makes things less blurry on hidpi setups. Tested on macOS and with `SDL_VIDEODRIVER=wayland`
=> sdl: set SDL_WINDOW_ALLOW_HIDPI

32blit-config.cmake, 32blit-pico/CMakeLists.txt, 32blit-sdl/CMakeLists.txt, 32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, firmware-update/CMakeLists.txt
Recently, trying to `pip install 32blit` results in:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.11/README.venv for more information.
note: If you believe this is a mistake, please contact …
```
=> Search for the 32blit executable if the module fails

32blit/graphics/blend.cpp, 32blit/graphics/blend.hpp, 32blit/graphics/surface.cpp, 32blit/graphics/surface.hpp, 32blit/graphics/tilemap.cpp
After repeating my "blit that is actually a fill" optimisation for the third time, I worked out a way to avoid it entirely and improve TileMap perf a bit. Also adds a useful `get_pixel` method to `Surface` (returns the pixel converted to a `Pen`).
I haven't benchmarked the change to `stretch_blit`, but I'd expect a similar effect there.
(Making the blit code smaller is also a good thing for the firmware)
=> Add Surface::get_pixel and remove special case from blit code

32blit-pico/CMakeLists.txt, 32blit-pico/board/vgaboard/config.cmake, 32blit-pico/board/vgaboard/config.h, 32blit-pico/ffconf.h, 32blit-pico/file.cpp, 32blit-pico/spi.pio, 32blit-pico/storage.cpp, 32blit-pico/storage.hpp, 32blit-pico/storage_flash.cpp, 32blit-pico/storage_sd_spi.cpp
This was the first thing in my branch after the latest rebase. Only includes the SPI driver, not the native SD driver (that still has issues).
=> pico: SPI-mode SD card support

32blit-pico/CMakeLists.txt
Unused, probably copied from 32blit-stm32. 
Just a random thing spotted while in the area...
=> pico: remove blit_executable_common

32blit/graphics/surface.cpp
Copy the code for stretch_blit and remove the x logic.
For raycaster (one of the two users):
- -2 ms on 32blit
- -6 ms on PicoSystem
- -27 ms (ish) on PicoVision (drawing vertically is still bad for perf)
A lot of the improvements can also be gained by replacing the contents of `stretch_blit_vspan` with `stretch_blit(src, {uv, Size{1, sc}}, {p, Size{1, dc}});`. Probably because I already optimised that a lot.
=> Optimise stretch_blit_vspan

32blit-pico/led.cpp
Otherwise the LED is never going to get enabled (broken by #827 as this file still compiles without its #defines, it just does nothing)
=> pico: include config in led.cpp

32blit-pico/input_usb_hid.cpp, 32blit-pico/usb_host.cpp
+ extra code to handle not having a dpad and mapping the stick to the dpad. Tested on the picovision-and-everything-else branch.
(The other controller is probably going to involve a tinyusb issue...)
=> pico: 8BitDo Zero 2 HID mapping

32blit-config.cmake, 32blit-pico/CMakeLists.txt, 32blit-sdl/CMakeLists.txt, 32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, firmware-update/CMakeLists.txt
Someone thought using a build dir with () in it was a good idea, resulting in a lot of
```
/bin/sh: -c: line 1: syntax error near unexpected token `('
```
Adding this magic flag ~~allows them to continue making poor choices~~ fixes that problem.
Also the CMake docs say that this is a good idea:
Use of VERBATIM is recommended as it enables correct behavior.
=> Add VERBATIM to CMake custom commands

32blit-pico/config.h, 32blit-pico/display.cpp, 32blit-pico/display.hpp, 32blit-pico/display_none.cpp, 32blit-pico/display_scanvideo.cpp, 32blit-pico/display_st7789.cpp, 32blit-sdl/System.cpp, 32blit-stm32/Src/display.cpp, 32blit/engine/engine.cpp, 32blit/graphics/surface.hpp
Non-picovision screen-related changes from that branch (in an attempt to clean it up to not break other things).
Most break-y change is always using `set_screen_mode_format` at the API level to simplify some stuff. (Could probably delete the old one from -sdl/-pico after this).
Tested on SDL, 32blit, PicoSystem and VGA board... I think.
(Still not sure about `(PixelFormat)-1`, but also didn't want to think about `Surface(..., PixelFormat::Default)` being a thing)
=> Some screen mode refactoring

32blit-sdl/CMakeLists.txt
Boilerplate macOS builds are failing (on release or if you have added artefacts), probably due to some update in brew's SDL build (?). This should fix it (it does locally).
The SDK itself is unaffected as it uses a fixed version of the SDL framework. (Which also allows arm builds... not that I have anything to run those on)
=> sdl: add extra search dir for fixup_bundle

32blit-pico/CMakeLists.txt
The pico SDK sets a default program name if PICO_PROGRAM_NAME is not set. As we're specifying all the metadata using bi_decl directly, disable the fallback.
=> Fix pico metadata title

32blit-pico/display_picovision.cpp, 32blit-sdl/Renderer.cpp, 32blit-sdl/Renderer.hpp, 32blit-sdl/System.cpp, 32blit-stm32/Src/display.cpp, 32blit/engine/engine.cpp, 32blit/engine/engine.hpp
First commit is enough to allow non-default modes by setting `DISPLAY_WIDTH/HEIGHT` to the desired `hires` resolution. The next three are so you can do it at runtime (or at least try to, non-picovision returns false for anything not the defaults).
Works most of the time... sometimes my mode test gets the red screen of death, but attempting to manually reproduce usually doesn't...
(+ bonus SDL cleanup because I was going to add more modes then realised it wouldn't be as simple as I thought)
=> More PicoVision modes

32blit/engine/api_private.hpp, firmware/firmware.cpp, launcher/launcher.cpp
This is a few patches shared by the "SDL launcher" and "pico launcher" branches. Moves checking if a file can be launched over to the "firmware" side. Should allow better compatibility checks when combined with #822 (and less "Oops!").
Also makes it a little easier to implement alternative launchers. (Which _may_ be what made me dig these up...)
=> Add can_launch API

32blit-stm32/executable.cmake, 32blit-stm32/startup_user.S, 32blit/engine/api_private.hpp, 32blit/engine/api_version.h, firmware/firmware.cpp, launcher-shared/executable.hpp, launcher/launcher.cpp
Some patches from the pico launcher/api stuff. Adds a device id and the api version to the .blit file header, taking advantage of there being an unused constant `00 00 00 90` at the end for backwards compatibility (first byte is repurposed as device id, non-0 means the api info is there).
I have no idea where the name "STM32Blit" came from though. Should probably be something like STH32H7 (existing .blits are built for cortex-m7 and assume STM32 RAM layout, though there isn't a loader for anything that isn't a 32blit...)
=> Extend .blit header with api/device info

32blit-pico/audio/pwm.cpp
Probably unnoticed because nobody uses this. (... and I apparently don't test it...)
=> pico: unbreak PWM audio

32blit-pico/audio/pwm.cpp
Only worked if it we were using PIO1 (not the default) and happened to choose SM1.
=> pico: unbreak pwm harder

.github/workflows/Emscripten.yml, .github/workflows/Visual Studio.yml, .github/workflows/cmake.yml
The usual version bumps for deprecation warnings, plus the ubuntu version as 20.04 is EOL next year (may also solve a problem I'm having)...
Need to make sure there are no surprises from the compiler version bump (though I'm locally using 14.1 so I hope not). Also might not want to use latest ubuntu to ensure wider compatibility :thinking: 
(22.04 is an arm gcc bump from 9 -> 10, 24.04 is -> 13)
=> Actions updates

32blit-sdl/CMakeLists.txt
Because the library link is PUBLIC, when we have a new SDL2 with the targets defined, the include dirs also end up public. Change this in the fallback path for consistency.
This change is a result of me needing to call an SDL function in something as a workaround, which built fine locally... but blew up the actions build.
=> sdl: make include directories PUBLIC in fallback path

32blit-sdl/System.cpp, 32blit-sdl/System.hpp
Instead of at 100Hz. Seems I broke this in #752... Only noticed because I hacked the video capture code back to life (again) and got a 2x slow video.
=> sdl: copy/present only after rendering

32blit-pico/input/gpio.cpp, 32blit-pico/input/usb_hid.cpp, 32blit-pico/led.cpp, 32blit-pico/main.cpp, 32blit-pico/multiplayer.cpp, 32blit-sdl/Audio.cpp, 32blit-sdl/Multiplayer.cpp, 32blit-sdl/System.cpp, 32blit-stm32/CMakeLists.txt, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/32blit/i2c.cpp, 32blit-stm32/Src/api.cpp, 32blit-stm32/Src/multiplayer.cpp, 32blit-stm32/Src/sound.cpp, 32blit-stm32/executable.cmake, 32blit.toolchain, 32blit/audio/audio.hpp, 32blit/engine/api.cpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp, 32blit/engine/multiplayer.cpp, firmware/firmware.cpp
Split the API struct into a "const" and "data" part. This is a result of me not wanting to reserve 2K of RAM on pico. After this, all the function pointers can be constants (may improve #484) and the data part only needs 64 bytes.
For compatibility, 32blit-stm32 is still using the old layout by inserting padding and overlaying the two structs on top of each other.
These are (I think) the only remaining non-pico changes on my big pico branch.
=> API refactor

32blit/engine/api_private.hpp
There aren't any 64-bit members in these structs so this should have no affect on 32-bit platforms and the packing is causing problems with misaligned pointers on (mac) arm64.
Should fix this error:
`ld: building fixups: pointer not aligned at __ZL14blit_api_const+0x4 from 32blit-sdl/libBlitHalSDL.a[10](System.cpp.o)`
=> Don't force 4-byte alignment on api structs

32blit/graphics/primitive.cpp
I had it hang again, so fixed it.
Instead of checking if we've reached the target, count how many pixels we should draw. I've verified that this is the same number of iterations (except not infinite sometimes) and is possibly a little faster (it certainly generates less code).
Fixes #504 ?
=> Fix Surface::line infinite loops

.github/workflows/cmake.yml
Switch from the long deprecated upload-release-asset to action-gh-release and attempt to replicate the same behaviour.
Avoids nodejs and set-output deprecation warnings:
- https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I've put this off for too long! `upload-release-asset` has been deprecated and unmaintained for years, causing a growing number of warnings in the Actions output.
Test release: https://github.com/32blit/32blit-sdk/releases/tag/TEST-DO-NOT-EAT
=> CI: Switch to action-gh-release.

32blit-pico/config.h, 32blit-pico/main.cpp, 32blit-pico/storage.hpp, 32blit-pico/storage/flash.cpp, 32blit-pico/storage/sd_spi.cpp, 32blit-pico/usb/device.cpp
First patch finally replaces the "storage available" stub with an actual implementation and doesn't claim there's storage if there's no card detected.
Second fixes the USB MSC code to report no medium if no card, which stops the host from polling repeatedly, causing timeouts reading the non-existent card and upsetting everything.
Third optimises block reads a bit, mostly because it ended up slightly too slow on RP2350 causing frequent read corruption. (That part should maybe be using DMA)
(Still need to update SD code to not assume clock is 125 or 250MHz, but it's currently working okay because we overclock everything to 250 still...)
=> pico: SD storage fixes

32blit-sdl/CMakeLists.txt
Fixes this:
```
CMake Error at /opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/BundleUtilities.cmake:458 (message):
otool -l failed: 1
error:
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic:
can't open file: @rpath/libjxl_cms.0.11.dylib (No such file or directory)
Call Stack (most recent call first):
/opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/BundleUtilities.cmake:527 (get_item_rpaths)
/opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/BundleUtilities.cmake:649 (set_bundle_key_values)
/opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/BundleUtilities.cmake:933 (get_bundle_keys)
/Users/runner/work/super-blit-kart/main/build/fixup.cmake:3 (fixup_bundle) …
```
=> sdl: fix installing on macos with sdl_image from homebrew

.github/workflows/cmake.yml, 32blit-pico/CMakeLists.txt, 32blit-pico/board/pimoroni_picovision.h, 32blit-pico/sdk_import.cmake, docs/pico.md
Set the magic variable so we can have local board headers and add a minimal picovision header so we can do `-DPICO_BOARD=pimoroni_picovision` instead of `-DPICO_BOARD=pico_w -DPICO_ADDON=pimoroni_picovision`. This also makes the board metadata in the UF2 more useful.
=> Make building for boards that don't have headers in the SDK easier

32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, CMakeLists.txt, firmware/CMakeLists.txt, launcher/CMakeLists.txt, utilities/CMakeLists.txt, utilities/hardware-test/CMakeLists.txt, utilities/picosystem-hardware-test/CMakeLists.txt
I'm getting a lot of `Compatibility with CMake < 3.10 will be removed from a future version of CMake.` warnings whenever I configure the examples. Specifying a maximum compatible version makes those go away. (CMake 3.27 removes `FindPythonInterp`, the replacement for that is `FindPython/FindPython3` but those require 3.12).
I also needed to fix how we compile asm files in 32blit-stm32 to be compatible with CMake 3.20, where setting the source `LANGUAGE` to CXX is interpreted as "compile as C++" not "use C++ compiler".
(We should maybe consider bumping the minimum version to clean some stuff up... I'm not sure how far back we're trying to support, but even Ubuntu 20.04 has 3.16 and Debian oldstable has 3.18)
=> Specify a max version in cmake_minimum_required to remove some warnings

32blit-pico/input/usb_hid.cpp
Some fixes to HID input to avoid random inputs sometimes and work around keyboards that also claim to be mice.
This doesn't improve the report parser to stop detecting mice as gamepads, but does allow using the keyboard anyway.
=> Pico HID fixes

32blit-pico/display/dbi.cpp
Noticed that we had `vsync_callback(vsync_callback)` as a result of my previous refactor. So this removes that silliness...
=> pico: inline dbi vsync_callback

docs/Linux.md
buster only has gcc-arm-none-eabi 7. Also bump the max as I'm currently using 14.
Technically already fixed, then broken again but... Fixes: #596
=> docs: update required Debian version

.vscode/cmake-kits.json
For consistency. Also makes it easier to check if your setup works. (Would need to add these to the global list to build anything other than the SDK/examples)
=> Add the other toolchains to the CMake kits list
