32blit-sdl/Main.cpp, 32blit-sdl/Makefile
Fixes:
* Now works on platforms other than windows.
* Doesn't use 100% CPU all the time.
* No mutex hassles.
* Better aspect ratio handling.
Btw, if you merge this, please don't squash it. There is useful information in the commit messages.
=> Fix up SDL HAL code

examples/doom-fire/doom-fire.cpp, examples/doom-fire/doom-fire.hpp
- This example implements the "Doom Fire", as described on this
blogpost: http://fabiensanglard.net/doom_fire_psx/
=> Adds the Doom Fire Example

README.md
The paths were wrong, added a few more words for clarity.
=> Fixed a typo, made the steps more clear.

README.md
Was using the already existing .hex file as the target output rather than a new .dfu file.
=> Fix dfu build command

README.md
Some more updates to the README.md file to help people get started
- Added info about Python3 and PIP3 and Python modules the user needs. I needed to install these modules into WSL myself.
- Added info about XMing
=> Added info about XMing and Python requirements

32blit-sdl/CMakeLists.txt, 32blit-sdl/Main.cpp, 32blit-sdl/System.cpp, 32blit-sdl/System.hpp
Don't know if you actually want this, but was working on SDL today and wondered how hard this would be...
[example](https://cupboard.daftgames.net/32blit/logo.html) (everything that gets built should be there)
=> Emscripten support for 32blit-sdl

README.md, docs/32blit.md, docs/Emscripten.md, docs/MacOSX.md, docs/VideoCapture.md, docs/Windows.md
As a result, README.md became much more simpler.
=> Moved documentation bits into the docs folder #47

CMakeLists.txt, examples/doom-fire/CMakeLists.txt, examples/fizzlefade/CMakeLists.txt, examples/flight/CMakeLists.txt, examples/geometry/CMakeLists.txt, examples/hardware-test/CMakeLists.txt, examples/logo/CMakeLists.txt, examples/matrix-test/CMakeLists.txt, examples/palette-cycle/CMakeLists.txt, examples/palette-swap/CMakeLists.txt, examples/particle/CMakeLists.txt, examples/platformer/CMakeLists.txt, examples/racer/CMakeLists.txt, examples/raycaster/CMakeLists.txt, examples/rotozoom/CMakeLists.txt, examples/scrolly-tile/CMakeLists.txt, examples/shmup/CMakeLists.txt, examples/sprite-test/CMakeLists.txt, examples/tilemap_test/CMakeLists.txt, examples/tilt/CMakeLists.txt, examples/tunnel/CMakeLists.txt
Just something I noticed while setting up a project.
=> Require at least CMake 3.1

32blit-sdl/System.cpp
=> Avoid using designated initialisers

docs/VisualStudio.md
Promised docs from #53. Also adjusted first sentence as it looked like it was saying you could build for the device with VS (at least to me).
=> Document alternative VS support using CMake+vcpkg

32blit/graphics/surface.hpp, vs/32blit-sdl/32blit-sdl.vcxproj, vs/32blit/32blit.vcxproj, vs/examples/doom-fire/doom-fire.vcxproj, vs/examples/fizzlefade/fizzlefade.vcxproj, vs/examples/flight/flight.vcxproj, vs/examples/geometry/geometry.vcxproj, vs/examples/hardware-test/hardware-test.vcxproj, vs/examples/logo/logo.vcxproj, vs/examples/matrix-test/matrix-test.vcxproj, vs/examples/palette-cycle/palette-cycle.vcxproj, vs/examples/palette-swap/palette-swap.vcxproj, vs/examples/particle/particle.vcxproj, vs/examples/platformer/platformer.vcxproj, vs/examples/racer/racer.vcxproj, vs/examples/raycaster/raycaster.vcxproj, vs/examples/rotozoom/rotozoom.vcxproj, vs/examples/scrolly-tile/scrolly-tile.vcxproj, vs/examples/shmup/shmup.vcxproj, vs/examples/sprite-test/sprite-test.vcxproj, vs/examples/tilemap_test/tilemap_test.vcxproj, vs/examples/tilt/tilt.vcxproj, vs/examples/timer-test/timer-test.vcxproj, vs/examples/tunnel/tunnel.vcxproj, vs/examples/tween-test/tween-test.vcxproj
Changes for consistency with the CMake build. Mentioned in #50.
=> VS cleanups

README.md, docs/Linux.md
Added links to the main README.md file to point to the other doc files directly using the linking mechanism supported by Github.
Also fixed a small style thingy in the Linux file.
=> Linked to other docs from the main README

32blit-sdl/Main.cpp
This fixes controllers in Emscripen builds (not detected until a button is pressed) and also helps with my slightly broken cables...
=> Handle controller connect/disconnect

32blit/32blit.hpp, 32blit/engine/tweening.cpp, 32blit/graphics/mode7.cpp, 32blit/types/mat3.cpp, 32blit/types/mat4.cpp, examples/geometry/geometry.cpp, examples/particle/particle.cpp, examples/tilt/tilt.cpp, examples/tunnel/tunnel.cpp
Now less than 100!
I was tempted to create a `blit::pi` constant instead of messing with `M_PI`.
(BTW, something I noticed while doing this is that `mat4::rotation` takes degrees and `mat3::rotation` takes radians)
=> Fix some warnings

32blit-stm32/CMakeLists.txt, 32blit.cmake, 32blit.toolchain, README.md, docs/32blit.md, docs/Emscripten.md, docs/Linux.md, docs/VideoCapture.md, docs/VisualStudio.md, docs/Windows.md, docs/macOS.md, examples/platformer/platformer.cpp, vs/game/CMakeLists.txt
Some of this is stuff I mentioned in other PRs, the rest is just things I noticed.
=> Misc small changes

docs/Linux.md
Add a line to install required tools
=> Update Linux Docs

32blit-sdl/Main.cpp
Caused by the Emscripten support, oops.
=> Fix building with video capture

docs/Windows.md
Missing space was breaking the URL.
=> Fix broken link in Windows.md

32blit-stm32/Src/fatfs_sd.c
This gets the 2GB card I have to work (mostly, I had to change the prescaler).
=> Fix non-high capacity V2 SD cards

.travis.yml, examples/CMakeLists.txt, vs/sdl/sdl2-config.cmake
Should cover the most likely to break builds. Windows is a bit weird, but seems to work (Just don't look at the build output.)
=> More Travis!

32blit-stm32/CMakeLists.txt
I don't think these are useful.
=> Don't build .dfu files for external flash builds

examples/CMakeLists.txt
So we can all listen to the masterpiece
=> Build audio-test

.travis.yml, vs/32blit.sln, vs/examples/scrolly-tile/scrolly-tile.vcxproj
Fixes the VS solution build, then adds it and MinGW to Travis. Also labels the builds.
=> Even more Travis

32blit/graphics/surface.hpp, 32blit/graphics/text.cpp, examples/text/text.cpp
Follow up to #75. I tried to make the clip rect default to something sensible. Also fixes some wrapping bugs.
Also indirectly fixes flash-loader blowing up when you have too many files.
=> Text improvements 2

32blit-stm32/CMakeLists.txt, 32blit.cmake, docs/32blit.md, tools/src/32Blit.cpp, tools/src/CMakeLists.txt
Not quite finished, but opening a PR to more easily track progress. The current state is that I can run:
```
cmake -B build.stm32 -G Ninja -DCMAKE_TOOLCHAIN_FILE=./32blit.toolchain -DFLASH_PORT=/dev/serial/by-id/usb-STMicroelectronics_32Blit_CDC_305E39803437-if00
ninja -C build.stm32 raycaster.flash
```
And have an example on the device. 
The code shuffling commit is going to be/cause rebase pain for anyone working on the 32Blit tool, sorry. (If anyone wants to merge something, I'll rebase.)
=> Flash targets

.travis.yml, 32blit-sdl/CMakeLists.txt
Might as well add the last one. I needed the first commit to build locally as well, it's a bit of a mess though.
=> macOS travis

docs/macOS.md
=> mac doesnt have wget

.gitignore
Adds the github provided CMake ignore list to the bottom of .gitignore.
=> Add CMake gitignore.

docs/Linux.md, docs/VSCode.md
I keep mentioning my VS Code setup, might as well document it. I expect someone to find a typo in there somewhere...
=> VS Code setup docs

tools/src/32Blit.cpp
It would try to reconnect to AUTO instead of the detected port...
=> Fix reconnecting with AUTO port

docs/VSCode.md
added /cmd to idiot-proof for us mac types
=> mac shortcuts

docs/32Blit-Firmware.md
also added link to flash loader doc
=> changed [ brackets to ( brackets so the links work. 

firmware/flash-loader/flash-loader.cpp, firmware/flash-loader/flash-loader.hpp
Just a couple of small quality of life tweaks before we overhaul the UI:
- Wrap the cursor from top/bottom bottom/top
- Allow dpad direction to be held to rapidly skip through titles
- Slightly indent text and vertically center-align in the selection box
=> Tweak Firmware

docs/macOS.md
...with pip3 dependency list missing as i don't know what they are 🤷‍♂️
I added a sentence in there about checking if you already have it installed as (i think) it's fairly common for people to already have it, but possibly through some other method (gem?), so ideally this will reduce the issue of having a conflicting install
=> some python3 install instructions 

32blit/graphics/color.cpp, examples/tween-test/tween-test.cpp
=> graphics-rework: update remaining example

examples/hardware-test/hardware-test.cpp, examples/scrolly-tile/scrolly-tile.cpp, examples/timer-test/timer-test.cpp, examples/tween-test/tween-test.cpp, tools/src/32Blit.cpp
Another "I was on Windows" PR. Gives Visual Studio one less thing to complain about and is probably a good idea anyway.
=> Use snprintf

docs/32Blit-Loader.md
doh. totally forgot to commit this change too from last night.
=> Added in some additional info.

README.md, docs/32Blit-Loader.md, docs/32blit.md
Probably not done with this, but it's getting late and I'll probably start writing complete nonsense soon... Also, opening this to hopefully avoid anyone changing the same things.
=> Misc docs updates

docs/VSCode.md
More work for #139. Turns out writing documentation is hard. (Someone give me some code to write... please?).
Anyway, this requires #159 for Windows to work. I haven't tested if the arm toolchain file works with an appropriate (windows) toolchain in the PATH, but it does work if you use the "Remote - WSL" extension (which is to be expected since it's effectively running on Linux then...)
=> Further VS Code docs

32blit-sdl/System.cpp
I was attempting to stream audio from the SD card, and this was helpful for debugging.
=> Implement open/read/close_file for SDL

32blit-stm32/Src/32blit.c
Avoid seeking if we're already there. Helps a bit with my streaming demo.
=> Optimise read_file a little

CMakeSettings.json, docs/Windows-VisualStudio.md
It now uses the same SDL as the solution (and using VS Code). It also adds the Debug/Release, x86/x64 build configurations as default.
=> Improve VS "Open Folder" build

32blit-sdl/CMakeLists.txt, 32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-sdl/System.cpp, 32blit-stm32/CMakeLists.txt, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/file.cpp, 32blit.cmake, 32blit/32blit.hpp, 32blit/engine/engine.cpp, 32blit/engine/engine.hpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp, vs/32blit-sdl/32blit-sdl.vcxproj, vs/32blit-sdl/32blit-sdl.vcxproj.filters, vs/32blit/32blit.vcxproj
You probably already know what I needed this for :smile: . Took some time to get all the Windows builds happy.
=> FIle listing

32blit/audio/audio.cpp, 32blit/audio/audio.hpp, examples/audio-wave/audio-wave.cpp
Helpful when your callback is a class member...
=> Add an argument to the wave callback

32blit/graphics/font.hpp
=> Fix warning I just added

32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-sdl/System.cpp, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/file.cpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp
Another useful file API addition.
=> Add a function to get file length

tools/map-builder, tools/sprite-builder
Some more path tomfoolery to handle requirements of invoking Tiled.exe in different situations.
=> More fixes to tooling, fixups for paths in map-builder

32blit-sdl/File.cpp
Bit of a corner case, but managed to hit it...
=> Fix list_files for symlinked directories

32blit-stm32/startup_stm32h750xx.s
Mostly a copy/paste of the .data init. My assembly skills don't extend much past (barely) reading it... But this does work.
=> Add ITCM init to startup

32blit-stm32/Inc/persistence.h, 32blit-stm32/Src/fatfs_sd.c
Split out the SD card fixes from #204 as it would be a good idea to merge these first.
=> SD Card fixes

32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/file.cpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp, examples/another-world/another-world.cpp
The part that breaks everyone's code. Ports the one example using files, shuffles code around to hide the old API then does some cleanup. Also fixes a small leak. (I can drop the last commit if the pointers are important for something.)
Edit: best viewed with whitespace changes hidden: https://github.com/pimoroni/32blit-beta/pull/219/files?w=1
=> Class based file API - part 2

docs/VSCode.md
Forgot about these ones. I don't know if we need anything else for #139?
=> Small VS code docs changes

32blit-stm32/CMakeLists.txt, 32blit-stm32/Inc/USBManager.h, 32blit-stm32/Inc/main.h, 32blit-stm32/Inc/usb_device.h, 32blit-stm32/Inc/usbd_storage_if.h, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc.h, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_bot.h, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_data.h, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_scsi.h, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc/usbd_msc_storage_template.h, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c, 32blit-stm32/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.c, 32blit-stm32/Src/CDCLogging.c, 32blit-stm32/Src/USBManager.cpp, 32blit-stm32/Src/main.c, 32blit-stm32/Src/usb_device.c, 32blit-stm32/Src/usbd_desc.c, 32blit-stm32/Src/usbd_msc_scsi.c, 32blit-stm32/Src/usbd_storage_if.c, firmware/flash-loader/flash-loader.cpp, firmware/flash-loader/flash-loader.hpp
#204. Rebased since I've caused conflicts for it at least twice. Also drops the eclipse stuff.
=> Rebased Mass Storage

docs/Windows-VisualStudio.md, template/game.cpp
I copied the template and it did not compile. I figured this was out of date ? So I - hopefully - fixed it.
=> Fixed template

32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-sdl/System.cpp, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/file.cpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp
The main addition here is writing. Also adds directory creation and existence checks.
=> More file API additions

32blit-sdl/File.cpp
=> Fix file mode comparison

32blit/CMakeLists.txt, 32blit/engine/version.cpp, 32blit/engine/version.hpp, 32blit/version_defs.hpp.in, examples/logo/logo.cpp, vs/32blit/32blit.vcxproj, vs/32blit/32blit.vcxproj.filters, vs/32blit/version_defs.hpp
A bit of a WIP as I'm not sure where the defines/header should go (probably somewhere internal). Also, left a test commit in, and VS is broken. Inspired by #216. 
Test release here: https://github.com/Daft-Freak/32blit-beta/releases/tag/1.2.3
=> Generate version number defines

32blit-sdl/CMakeLists.txt
Shaves a bit off the .js and makes JPEG loading actually work... which adds ~150k to the .wasm.
=> Minor Emscripten changes

.travis.yml
Have some extra warnings :smile:
=> Run clang-tidy on the Linux travis build

32blit-stm32/Src/32blit.c
My blit was buzzing constantly after losing power completely. Finally realised it wasn't the speaker...
=> Init vibration

32blit/graphics/surface.hpp, 32blit/graphics/text.cpp
(Worse) alternative to #255 that works on the old arm compiler...
=> Use const string refs for the text functions

32blit-stm32/Src/32blit.c
Fixes the random LED colour after #281 and should also be useful for #269.
=> More shared API data init

32blit/engine/profiler.cpp, 32blit/engine/profiler.hpp, 32blit/engine/running_average.hpp
Added clear_all_probes() to reset all probes to init state.
Some fixes to actually clear the probes correctly.
=> Clearing probes fixes.

32blit.toolchain, template/CMakeLists.txt
Sets a couple of extra variables in the toolchain to help with configuring out-of-tree projects.
=> Toolchain tweaks

32blit-sdl/File.cpp, 32blit-sdl/File.hpp, 32blit-sdl/System.cpp, 32blit-stm32/Inc/file.hpp, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/file.cpp, 32blit/engine/api_private.hpp, 32blit/engine/file.cpp, 32blit/engine/file.hpp
File API again! Using these to help with save corruption in my emulator...
=> File rename/remove

32blit/graphics/surface.hpp
Travis build broke on an unrelated change. Maybe an update?
=> Fix VS build

.travis.yml, ci/install_sdl_macos.sh, ci/install_sdl_mingw.sh, ci/install_sdl_vs.sh
Updates the STM32 build to the new Ubuntu to get a better compiler without needing the PPA. Also splits out the SDL install scripts as they're getting a bit big. (I _may_ have something that requires adding more to them somewhere...)
=> A few Travis changes

32blit-stm32/Src/32blit.c, 32blit/engine/api.cpp, 32blit/engine/api.hpp, 32blit/engine/api_private.hpp, 32blit/engine/engine.cpp, 32blit/engine/input.cpp, 32blit/engine/input.hpp, examples/profiler-test/profiler-test.cpp, examples/scrolly-tile/scrolly-tile.cpp, examples/text/text.cpp, examples/voxel/voxel.cpp, firmware/flash-loader/flash-loader.cpp
Roughly what was suggested in #63.
=> Button API improvements

32blit-stm32/Src/fatfs_sd.c
Replaces the SPI functions for accessing the SD card with simpler more direct versions. Improves read speed by up to 7x on my new card and ~2x on my old one.
Possibly needs some testing on more cards, but doesn't cause the cards I tested with to stop working. I've also tested that mass storage still works, since it was previously broken by changes here. (It isn't any faster though...)
[test bins](https://github.com/pimoroni/32blit-beta/files/5074139/sd-test.zip)
Before/After:
Fixes #1?
=> Make SD cards fast

32blit-sdl/CMakeLists.txt, 32blit-sdl/File.cpp, 32blit-sdl/Main.cpp, 32blit-stm32/Inc/ffconf.h, 32blit-stm32/Src/32blit.c, 32blit-stm32/Src/file.cpp, 32blit-stm32/Src/usbd_storage_if.c, 32blit/audio/audio.cpp, 32blit/engine/engine.cpp, 32blit/engine/file.hpp, 32blit/engine/profiler.cpp, 32blit/graphics/text.cpp, 32blit/types/vec2.hpp, examples/particle/particle.cpp, examples/raycaster/raycaster.cpp, examples/tunnel/tunnel.cpp, firmware/flash-loader/flash-loader.cpp, firmware/flash-loader/flash-loader.hpp
... and a couple of minor additions pulled out of various branches.
=> Misc fixes/cleanups

32blit-stm32/Inc/32blit.h, 32blit-stm32/Src/32blit.c, firmware/flash-loader/flash-loader.cpp, firmware/flash-loader/flash-loader.hpp
More stuff from my mega-branch that doesn't depend on #269. Mostly ~stealing~ manually applying changes from `flash-loader-work` for the nice progress bar/scrolling list. (Fixes #276)
=> Firmware UI stuff

32blit-sdl/Audio.cpp
I only tested the offset change on device...
=> Fix SDL audio

32blit/engine/particle.cpp, 32blit/engine/particle.hpp
I think this is the only thing not in there.
=> Move particle classes to the namespace

32blit-stm32/CMakeLists.txt, firmware/firmware.cpp, firmware/firmware.hpp
Just a minor annoyance... Also fixes the opt level to what I thought it was, which avoids this change increasing size by a few kB...
=> Sort firmware file list on init

32blit/engine/file.cpp, 32blit/engine/file.hpp, 32blit/graphics/font.hpp, 32blit/graphics/jpeg.cpp, 32blit/graphics/jpeg.hpp, 32blit/graphics/sprite.hpp, 32blit/graphics/surface.hpp, 32blit/graphics/text.cpp
I think I wrote these while waiting for Travis builds... Adds at least SOME documentation to the file/text/font/jpeg APIs.
=> Attempt to document some of my API additions

firmware/firmware.cpp
Back to being readable. Also move it in a bit.
=> Fix "No Files Found" message

.travis.yml
The CMake one already did this, should fix the build.
=> Specify Python version for the VS sln build

32blit-stm32/Inc/executable.hpp, 32blit-stm32/Src/32blit.cpp, 32blit-stm32/startup_user.cpp, 32blit/engine/api_private.hpp
Break everything. Needs some checking somewhere.
=> WIP: Add a version field to the API section

docs/32blit.md
...and remove a few references to the old tool. Might need a big "DO NOT UPLOAD GAMES USING DFU" somewhere.
=> Expand uploading docs

32blit-stm32/Inc/32blit.h, 32blit-stm32/Src/32blit.cpp, firmware/firmware.cpp
Handles inserting/removing the SD card without needing to reset. Also displays a different message in the menu for no card detected.
=> SD card insert/remove detection

32blit-stm32/CMakeLists.txt, 32blit-stm32/executable.cmake, 32blit.cmake
Fail CMake configure if the tools are not installed instead of blowing up later.
=> Check if the tools are installed

32blit/CMakeLists.txt, CMakeLists.txt
So much noise, just give up and disable that warning. You can decide if this is a good idea :smile:
=> Disable VS "conversion from X to Y, possible loss of data" warning

docs/Tools.md
I went here to add something for fonts as I don't think that's documented anywhere. May have got a bit carried away...
Almost guaranteed to have some typos somewhere.
=> Documentation for asset options

32blit-stm32/Src/display.cpp
This should avoid displaying distorted frames with the wrong mode.
This demo switches between modes constantly, and can be used to see the improvement: [screen-mode.zip](https://github.com/pimoroni/32blit-beta/files/5560113/screen-mode.zip)
(Also, it looks like the rightmost column of the screen is missing...)
=> Delay parts of screen mode switching

32blit-sdl/CMakeLists.txt
=> Generate/use icns for macOS bundles

32blit-stm32/Src/fatfs_sd.c
Managed to get even more speed out of this...
Tested on _three_ cards this time (all MB/s):
- 2.32 -> 2.42
- 5.68 -> 6.47
- 5.84 -> 6.67
Fastest is ~53Mbits, which is getting pretty close to the 60MHz clock.
=> Make SD reads even faster

32blit-stm32/executable.cmake
Noticed the release contained the non-reloc'd bins.
(Another reminder to change this to a nicer ext...)
=> Install the right bins

32blit-stm32/executable.cmake, docs/32Blit-Loader.md, docs/32blit.md, firmware/firmware.cpp
Fix another `.bin`/`.reloc.bin` fail... then kill `.reloc.bin` and replace it with `.blit`.
=> Fix flash targets and use .blit as the game file extension

firmware/firmware.cpp
This could not have had a better PR number.
=> Fix the compare to find .blit

.github/workflows/cmake.yml, CMakeLists.txt
This should make it easier to include things that aren't binaries... May also be useful for the boilerplate.
=> Use CMake to generate the release zip/tar

32blit-stm32/Src/display.cpp
Use a few of the defines to make it a little less magic.
=> Less magic DMA2D

32blit-sdl/CMakeLists.txt, 32blit-stm32/executable.cmake, 32blit.cmake, 32blit.toolchain, CMakeLists.txt, dist/LICENSE, dist/README
Could probably stand to have some basic docs here, but some stuff might necessarily be platform dependent, ie:
1. instructions for installing games/flashing firmward in blit release
2. instructions for joining/hosting multiplayer (2 player) in SDL releases
3. ???
=> Adds LICENSE and README to dist for #376

32blit-stm32/Inc/main.h, 32blit-stm32/Src/main.c
Forgot to push this before I merged :facepalm: 
Got distracted by Google Blob Opera :laughing:
=> Remove redundant charge_led_counter

examples/platformer/platformer.cpp
I stole most of the collision detection logic from Rainbow Ascent for this, and fixes some magic number stuff that made collision not really very easy to reason about.
Right now it's still pretty heinous and we probably need a better example, but it *feels* okay. And maybe that's all that matters :laughing:
=> Make Platformer actually.... platform!

examples/platformer/platformer.cpp
Unsure if the removed comparison should be an assignment, it seemed to work...
=> Fix platformer warnings

launcher/launcher.cpp
Should fix the other issue raised in #440
=> Fix selected item when item deleted

examples/mp3/mp3.cpp, examples/text/text.cpp
Can't really go around telling people they're indenting wrong when I've left a giant mess in one of the examples...
=> Fix some indentation in my examples

32blit-sdl/Main.cpp, launcher/launcher.cpp, launcher/launcher.hpp, vs/32blit.sln, vs/launcher-shared/launcher-shared.vcxproj, vs/launcher-shared/launcher-shared.vcxproj.filters, vs/launcher/launcher.vcxproj, vs/launcher/launcher.vcxproj.filters
So Windows freaks like myself can also work on the launcher project ;-)
=> Added Visual Studio projects for the launcher

launcher/CMakeLists.txt, launcher/contrib.hpp, launcher/credits.cpp, launcher/credits.hpp, launcher/launcher.cpp, launcher/launcher.hpp, launcher/update-contributors.py, vs/launcher/launcher.vcxproj, vs/launcher/launcher.vcxproj.filters
I moved my scrolling credits into the Launcher app. The contents of the scrolling is the same as before. Currently launches with the menu button. 
I have not added a menu yet, because I did not want a menu with just one item on it :-) But later if we need a separate menu, we can add the scrolling as one item there. 
Please comment, this is certainly not intended as the finished product -- if you have any comments, please share :-)
=> Scrolling project credits into the launcher

.gitignore, launcher/contrib.hpp
One of the leftover bits from #538. I was going to `.gitignore` it, but that doesn't work...
=> Placeholder the credits

firmware-update/metadata.yml.in, firmware/firmware.cpp, firmware/firmware.hpp
An attempt to de-duplicate and reorganise the flashing code in the firmware. There are a lot of things this could potentially break...
I've tested (at least I think):
SD flash installed
SD flash not installed
SD flash different version
CDC flash not installed
CDC flash installed
CDC flash different version
CDC flash launcher
CDC save
firmware update from SD
launcher update from SD
=> Some firmware refactoring

docs/macOS.md
Two elements needed to be installed.
I added the brew commands in the md file.
=> additional step for macOS

32blit-stm32/Src/fatfs_sd.c
Seems to reduce the setup time of "sd-test" by ~10ms on my "slow" card. (Doesn't seem to affect my "fast" card, it must be slow at writing).
(PR 0x100! :smile:)
=> Optimise SD writes too

docs/32Blit-Firmware.md
Add some stuff about firmware-update and launchers.
Things that probably need mentioned somewhere:
- WSL python tools needing a manual `--port /dev/ttySx` (matching the right COMx)
- Installing from releases
=> Firmware-related docs updates

site/examples/index.html
=> Add piano to emscripten example list

32blit-stm32/Src/32blit.cpp
Just fades out audio/the backlight after a period of inactivity. This was an experiment since there seems to have been a few mentions of sleep/low-power/screen-off recently...
Should maybe do something with the accelerometer?
=> Sort-of sleep mode

examples/doom-fire/doom-fire.cpp
- Updates the algorithm to update / render in a single loop.
- Adds wind to doom fire and binds left/right DPAD keys.
- Button X is used to stop / start the fire.
=> Improves the doom-fire demo

32blit-sdl/CMakeLists.txt, mingw.toolchain
Found this old branch with some attempts at fixing the MinGW fails in #483. It doesn't entirely fix that and fixes nothing with the current SDL version we're using... but is more correct (I think).
=> Some MinGW/SDL related fixes

32blit-stm32/Src/32blit.cpp
This fixes two (small) issues with the fade from "sleeping"
- If you held a button while fading in, the screen would stay black
- If you tried to cancel during the fade out, it would fade in from black
It would also increase the timeout... if I hadn't accidentally done that in the previous PR :facepalm:
=> Improve fade in from "sleep"

.github/workflows/cmake.yml
https://github.com/32blit/32blit-boilerplate/pull/17, but for the SDK.
=> Fix VS releases actually being debug builds

32blit-stm32/Src/32blit.cpp, 32blit/engine/api_private.hpp
Someone forgot that the API section isn't initialised... oops.
=> Actually init API versions/unbreak everything

examples/multiplayer/multiplayer.cpp
Adds a sequence number to each message, implements scrolling, and
shows a count of messages sent and received.
=> Make the multiplayer example a bit more interesting

docs/Windows.md
=> Fix python link in Windows.md

32blit/engine/save.hpp
Whoops, just got some redeclaration errors here...
=> Add missing #pragma once to save.hpp

32blit/graphics/surface.cpp
Another ~9ms in blit kart, won't affect the non-scaled case (different function). I think also fixes #221 (at least, it fixed something that looked like the same bug in blit kart).
The idea here is similar to the tilemap patch: fill multiple pixels at once if scaling up.
(I was a bit surprised when I measured this, thought it had a much smaller impact...)
=> Optimise stretch_blit_sprite

examples/tilemap-test/tilemap-test.cpp
Went here to change the lambdas to regular functions, ended up finding a bunch of other stuff...
=> Tilemap-test tidy

32blit-sdl/CMakeLists.txt, 32blit-sdl/File.cpp
These were the only SDK changes I needed to target Android. Also requires a [lot of extra boilerplate](https://github.com/32blit/32blit-sdk/files/6278580/android-project.zip) and a [pile of libraries](https://github.com/32blit/32blit-sdk/files/6278590/android-libs.zip)
(Of course, you can't play anything without a controller)
=> Android build fixes

docs/32blit.md
=> Fixed typo

docs/32Blit-Firmware.md
This at least covers the thing users want at the top. The rest may still need cleaning up...
=> Add release firmware install instructions

32blit-stm32/Src/32blit.cpp, 32blit-stm32/Src/CDCCommandStream.cpp, firmware/firmware.cpp
First two fix launcher updates (previously worked fine due to a reset). Third fixes the reloc parsing fix from #573 to handle another corner-case.
(Help, I can't escape from the flash/launch code!)
=> Flashing related fixes (again)

32blit-sdl/emscripten-shell.html, 32blit/graphics/surface.cpp, 32blit/math/geometry.cpp, 32blit/types/rect.hpp, docs/ChromeOS.md, examples/another-world/virtual-machine.cpp, examples/doom-fire/doom-fire.cpp, examples/flight/flight.cpp, examples/platformer/platformer.cpp, examples/raycaster/raycaster.cpp, examples/raycaster/raycaster.hpp, examples/saves/saves.cpp, examples/scrolly-tile/scrolly-tile.cpp, firmware/firmware.cpp
Result of running https://github.com/crate-ci/typos ... avoiding the "32blit-stm32" directory since it's a minefield.
=> Fix miscellaneous typos

launcher/launcher.cpp
Loads metadata for a file from a `.blmeta` file next to it. (Needs a way to generate that file, like [this](https://github.com/Daft-Freak/32blit-tools/commit/eff26443678cf57b1fd1cfc52b4176466ffac803))
[Test file for a Tetris rom](https://github.com/32blit/32blit-sdk/files/6677730/Tetris.gb.zip)
=> Metadata for files

32blit/types/rect.hpp
Tiny change to match everything else. (... and fix my build after const-ing some things)
=> Make Rect.size const

examples/scrolly-tile/scrolly-tile.cpp
* Shorten some text strings to fix on 120px mode
* Adjust text alignment to cozy up to left-hand edge
* Adjust letter spacing in title
* Add panning camera to fit 160px wide game onto 120px screen
* Fix x-axis collision to check aganist game bounds rather than screen bounds
=> Rainbow Ascent: Port to PicoSystem

firmware/firmware.cpp
Random late late night "that'll be easy" thought... and it was as soon as I actually flashed the modified firmware... :facepalm:  :yawning_face:
=> Reset sleep timer/wake up when receiving CDC data

32blit/audio/minimp3.h
=> Fix double promotion warning

docs/Firmware-Internals.md
More internal stuff, forgot to commit this after the last time someone asked.
=> Add memory layout to internals

.github/workflows/Emscripten.yml
Part 2 of fixing action warnings. (There wasn't an update for setup-emsdk when I wrote the other PR)
=> Update emscripten actions to fix deprecation warnings

firmware/firmware.cpp
The reloc header check returned ~0 instead of false... and leaked the file.
Also if file opening the file failed we'd leave the flash unmapped, so move the unmap after both.
=> firmware: fix launch early-out errors

32blit-pico/audio_i2s.cpp, 32blit-pico/audio_pwm.cpp, 32blit-pico/board/vgaboard/config.h, 32blit-pico/main.cpp
This should be all the relevant patches from my branches so that PicoVision support doesn't break VGA board (and also not require core1 to be enabled).
=> Pico audio improvements

.github/workflows/cmake.yml, vs/sdl/sdl2-config.cmake
Both a bit workaround-y, but I don't have Windows or macOS handy right now.
=> Fix actions

32blit-sdl/VideoCaptureFfmpeg.cpp
Just making this compile again...
=> Video capture fix

.github/workflows/cmake.yml
Probably should've actually merged this fix.
Fixes: #880
=> Fix ccache path

32blit-pico/audio/i2s.cpp, 32blit-pico/main.cpp
The old code ~wasn't demon-proof~ had some problems uncovered by running DOOM.
=> Pico I2S fixes

32blit-sdl/Input.cpp, 32blit-sdl/Input.hpp, 32blit-sdl/Main.cpp, 32blit-sdl/System.cpp
Fun little distraction from playing with sensors...
(Version check because I didn't want to bump the Emscripten version)
=> sdl: use controller accelerometer for tilt if available

32blit/32blit.hpp, 32blit/CMakeLists.txt, 32blit/audio/mp3-stream.cpp, 32blit/engine/output.cpp, 32blit/engine/output.hpp, vs/32blit/32blit.vcxproj, vs/32blit/32blit.vcxproj.filters
Just removing a pair of empty files and a no longer needed workaround. Also an mp3 fix.
=> Misc cleanup/fixes

32blit-pico/CMakeLists.txt, 32blit-pico/board/pimoroni_picovision.h, 32blit-pico/board/pimoroni_picovision/config.h, 32blit-pico/board/pimoroni_presto/config.cmake, 32blit-pico/board/pimoroni_presto/config.h, 32blit-pico/board/vgaboard/config.cmake, 32blit-pico/board/vgaboard/config.h, 32blit-pico/display/dbi.cpp, 32blit-pico/display/display_commands.hpp, 32blit-pico/display/dpi.cpp, 32blit-pico/display/dpi.pio, 32blit-pico/display/picovision.cpp, 32blit-pico/input/tca9555.cpp, 32blit-pico/main.cpp, 32blit-pico/storage/sd_spi.cpp
Involves adding a new DPI driver to replace scanvideo, also allowing the vgaboard to have `hires` on a Pico 2.
=> pico: Presto + QwST Pad
